'use strict';

// 保有食材のカテゴリ定義（キー: 食材ID, 値: 表示名）
const INGREDIENT_CATEGORIES = [
  {
    key: 'meat',
    label: '肉類',
    items: [
      ['pork', '豚肉'],
      ['chicken', '鶏肉'],
      ['beef', '牛肉'],
      ['chicken_mince', '鶏ひき肉'],
      ['pork_mince', '豚ひき肉'],
      ['mixed_mince', '合いびき肉'],
      ['bacon', 'ベーコン'],
      ['sausage', 'ウインナー'],
    ],
  },
  {
    key: 'egg_tofu',
    label: '卵・豆腐',
    items: [
      ['egg', '卵'],
      ['tofu', '豆腐'],
      ['atsuage', '厚揚げ'],
      ['natto', '納豆'],
    ],
  },
  {
    key: 'vegetable',
    label: '野菜（生・冷凍）',
    items: [
      ['onion', '玉ねぎ'],
      ['carrot', 'にんじん'],
      ['cabbage', 'キャベツ'],
      ['potato', 'じゃがいも'],
      ['nasu', 'なす'],
      ['tomato', 'トマト'],
      ['minitomato', 'ミニトマト'],
      ['cucumber', 'きゅうり'],
      ['piman', 'ピーマン'],
      ['moyashi', 'もやし'],
      ['negi', '長ねぎ'],
      ['garlic', 'にんにく'],
      ['ginger', 'しょうが'],
      ['mushroom', 'きのこ類'],
      ['daikon', '大根'],
      ['lettuce', 'レタス'],
      ['spinach_frozen', 'ほうれん草（冷凍）'],
      ['broccoli_frozen', 'ブロッコリー（冷凍）'],
      ['corn_frozen', 'コーン（冷凍）'],
    ],
  },
  {
    key: 'dried_can',
    label: '乾物・缶詰',
    items: [
      ['harusame', '春雨'],
      ['tuna_can', 'ツナ缶'],
      ['tomato_can', 'トマト缶'],
      ['katakuriko', '片栗粉'],
      ['rice', '米'],
      ['pasta', 'パスタ'],
      ['udon', 'うどん'],
      ['chuka_men', '中華麺'],
      ['panko', 'パン粉'],
      ['flour', '小麦粉'],
      ['hijiki', 'ひじき'],
      ['kiriboshi_daikon', '切り干し大根'],
    ],
  },
  {
    key: 'dairy',
    label: '乳製品',
    items: [
      ['cheese', 'チーズ'],
      ['milk', '牛乳'],
      ['butter', 'バター'],
      ['cream', '生クリーム'],
      ['yogurt', 'ヨーグルト'],
    ],
  },
];

// 調味料タブ定義
const SEASONING_TABS = [
  {
    key: 'japanese',
    label: '和',
    items: [
      ['soy_sauce', '醤油'],
      ['miso', '味噌'],
      ['mirin', 'みりん'],
      ['sake', '酒'],
      ['sugar', '砂糖'],
      ['dashi', 'だし'],
      ['vinegar', '酢'],
      ['mentsuyu', 'めんつゆ'],
    ],
  },
  {
    key: 'western',
    label: '洋',
    items: [
      ['salt', '塩'],
      ['pepper', 'こしょう'],
      ['olive_oil', 'オリーブオイル'],
      ['consomme', 'コンソメ'],
      ['ketchup', 'ケチャップ'],
      ['mayo', 'マヨネーズ'],
      ['worcester', 'ウスターソース'],
    ],
  },
  {
    key: 'chinese',
    label: '中',
    items: [
      ['oyster_sauce', 'オイスターソース'],
      ['doubanjiang', '豆板醤'],
      ['sesame_oil', 'ごま油'],
      ['chuka_dashi', '中華だし'],
      ['tenmenjan', '甜麺醤'],
    ],
  },
  {
    key: 'other',
    label: 'その他',
    items: [
      ['curry_roux', 'カレールー'],
      ['oil', '油'],
      ['ponzu', 'ポン酢'],
      ['dashi_soy', 'だし醤油'],
    ],
  },
];

// 料理データベース（100品: 和30 / 中30 / 洋30 / 他10）
const DISHES = [
  // ===== 和食 30品 =====
  { name: '肉じゃが', genre: '和', time: 30, need: ['pork', 'onion', 'potato', 'carrot', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '豚の生姜焼き', genre: '和', time: 20, need: ['pork', 'onion', 'ginger', 'soy_sauce', 'mirin', 'sugar'] },
  { name: '鶏の照り焼き', genre: '和', time: 20, need: ['chicken', 'soy_sauce', 'mirin', 'sugar', 'sake'] },
  { name: '肉豆腐', genre: '和', time: 20, need: ['beef', 'tofu', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '豚汁', genre: '和', time: 30, need: ['pork', 'daikon', 'carrot', 'negi', 'miso', 'dashi'] },
  { name: '筑前煮', genre: '和', time: 45, need: ['chicken', 'carrot', 'daikon', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '肉巻き野菜', genre: '和', time: 20, need: ['pork', 'carrot', 'piman', 'soy_sauce', 'mirin', 'sugar'] },
  { name: '親子丼', genre: '和', time: 20, need: ['chicken', 'egg', 'onion', 'soy_sauce', 'mirin', 'sugar', 'dashi', 'rice'] },
  { name: 'だし巻き卵', genre: '和', time: 10, need: ['egg', 'soy_sauce', 'sugar', 'dashi'] },
  { name: '豆腐ハンバーグ', genre: '和', time: 30, need: ['tofu', 'mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce'] },
  { name: 'すき焼き風煮', genre: '和', time: 30, need: ['beef', 'tofu', 'negi', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'sake'] },
  { name: '豚しゃぶサラダ', genre: '和', time: 20, need: ['pork', 'lettuce', 'cucumber', 'ponzu'] },
  { name: '鶏そぼろ丼', genre: '和', time: 20, need: ['chicken_mince', 'egg', 'soy_sauce', 'mirin', 'sugar', 'rice'] },
  { name: '厚揚げの煮物', genre: '和', time: 20, need: ['atsuage', 'daikon', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '豚バラ大根', genre: '和', time: 45, need: ['pork', 'daikon', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '鶏の唐揚げ', genre: '和', time: 20, need: ['chicken', 'soy_sauce', 'sake', 'ginger', 'garlic', 'katakuriko', 'oil'] },
  { name: 'じゃがいもの煮っころがし', genre: '和', time: 20, need: ['potato', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: 'なすの煮浸し', genre: '和', time: 20, need: ['nasu', 'dashi', 'soy_sauce', 'mirin'] },
  { name: 'ひじきの煮物', genre: '和', time: 30, need: ['hijiki', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '切り干し大根の煮物', genre: '和', time: 30, need: ['kiriboshi_daikon', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'] },
  { name: '豚しゃぶ鍋', genre: '和', time: 30, need: ['pork', 'cabbage', 'negi', 'mushroom', 'tofu', 'dashi', 'soy_sauce'] },
  { name: '焼き鳥丼', genre: '和', time: 20, need: ['chicken', 'negi', 'soy_sauce', 'mirin', 'sugar', 'sake', 'rice'] },
  { name: '和風ハンバーグ', genre: '和', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce', 'mirin', 'sugar', 'daikon'] },
  { name: '卵とじうどん', genre: '和', time: 20, need: ['udon', 'egg', 'negi', 'dashi', 'soy_sauce', 'mirin'] },
  { name: '肉うどん', genre: '和', time: 20, need: ['udon', 'beef', 'negi', 'dashi', 'soy_sauce', 'mirin', 'sugar'] },
  { name: '豚の味噌漬け焼き', genre: '和', time: 20, need: ['pork', 'miso', 'mirin', 'sugar', 'sake'] },
  { name: '厚揚げの照り焼き', genre: '和', time: 20, need: ['atsuage', 'negi', 'soy_sauce', 'mirin', 'sugar', 'katakuriko'] },
  { name: '鶏むね肉のマヨポン炒め', genre: '和', time: 20, need: ['chicken', 'mayo', 'ponzu', 'negi'] },
  { name: '豚肉と白菜風煮浸し', genre: '和', time: 20, need: ['pork', 'cabbage', 'dashi', 'soy_sauce', 'mirin'] },
  { name: '冷奴', genre: '和', time: 10, need: ['tofu', 'negi', 'soy_sauce'] },

  // ===== 中華 30品 =====
  { name: '麻婆豆腐', genre: '中', time: 20, need: ['tofu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'ginger', 'katakuriko', 'chuka_dashi'] },
  { name: '青椒肉絲', genre: '中', time: 20, need: ['beef', 'piman', 'oyster_sauce', 'soy_sauce', 'sugar', 'katakuriko', 'garlic'] },
  { name: '回鍋肉', genre: '中', time: 20, need: ['pork', 'cabbage', 'doubanjiang', 'miso', 'sugar', 'garlic'] },
  { name: '酢豚', genre: '中', time: 30, need: ['pork', 'piman', 'onion', 'carrot', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'katakuriko'] },
  { name: '餃子', genre: '中', time: 45, need: ['pork_mince', 'cabbage', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'katakuriko'] },
  { name: '春巻き', genre: '中', time: 30, need: ['pork_mince', 'harusame', 'carrot', 'cabbage', 'oyster_sauce', 'sesame_oil'] },
  { name: '中華丼', genre: '中', time: 20, need: ['pork', 'cabbage', 'carrot', 'mushroom', 'oyster_sauce', 'chuka_dashi', 'katakuriko', 'rice'] },
  { name: '麻婆春雨', genre: '中', time: 20, need: ['pork_mince', 'harusame', 'doubanjiang', 'soy_sauce', 'garlic', 'chuka_dashi'] },
  { name: '天津飯', genre: '中', time: 20, need: ['egg', 'tuna_can', 'katakuriko', 'chuka_dashi', 'soy_sauce', 'rice'] },
  { name: '棒々鶏', genre: '中', time: 20, need: ['chicken', 'cucumber', 'sesame_oil', 'soy_sauce', 'sugar', 'vinegar'] },
  { name: 'よだれ鶏', genre: '中', time: 20, need: ['chicken', 'negi', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'vinegar'] },
  { name: '鶏の甘酢あん', genre: '中', time: 20, need: ['chicken', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce'] },
  { name: '豚肉と厚揚げの中華炒め', genre: '中', time: 20, need: ['pork', 'atsuage', 'negi', 'oyster_sauce', 'garlic'] },
  { name: 'もやし玉子炒め', genre: '中', time: 10, need: ['egg', 'moyashi', 'negi', 'sesame_oil', 'salt', 'pepper'] },
  { name: '豚肉と白菜の中華煮込み', genre: '中', time: 20, need: ['pork', 'cabbage', 'mushroom', 'chuka_dashi', 'oyster_sauce', 'katakuriko'] },
  { name: '麻婆なす', genre: '中', time: 20, need: ['nasu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'katakuriko'] },
  { name: '担々麺', genre: '中', time: 20, need: ['chuka_men', 'pork_mince', 'doubanjiang', 'sesame_oil', 'chuka_dashi', 'miso'] },
  { name: 'ジャージャー麺', genre: '中', time: 20, need: ['chuka_men', 'pork_mince', 'tenmenjan', 'miso', 'garlic', 'katakuriko'] },
  { name: '八宝菜', genre: '中', time: 45, need: ['pork', 'cabbage', 'carrot', 'mushroom', 'moyashi', 'chuka_dashi', 'katakuriko', 'oyster_sauce'] },
  { name: '肉団子の甘酢あん', genre: '中', time: 30, need: ['mixed_mince', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'egg'] },
  { name: '中華風炒り豆腐', genre: '中', time: 20, need: ['tofu', 'egg', 'negi', 'oyster_sauce', 'sesame_oil'] },
  { name: 'ブロッコリー炒め', genre: '中', time: 10, need: ['broccoli_frozen', 'garlic', 'oyster_sauce', 'sesame_oil'] },
  { name: 'もやしと豚肉の中華炒め', genre: '中', time: 20, need: ['pork', 'moyashi', 'negi', 'oyster_sauce', 'sesame_oil', 'garlic'] },
  { name: 'あんかけ焼きそば', genre: '中', time: 30, need: ['chuka_men', 'pork', 'cabbage', 'carrot', 'mushroom', 'chuka_dashi', 'katakuriko', 'oyster_sauce'] },
  { name: '鶏肉と厚揚げの中華煮', genre: '中', time: 30, need: ['chicken', 'atsuage', 'negi', 'chuka_dashi', 'oyster_sauce', 'katakuriko'] },
  { name: '豚バラともやしのレンジ蒸し', genre: '中', time: 20, need: ['pork', 'moyashi', 'negi', 'sesame_oil', 'salt'] },
  { name: '卵とツナの中華炒め', genre: '中', time: 10, need: ['egg', 'tuna_can', 'negi', 'sesame_oil', 'oyster_sauce'] },
  { name: 'えのきの豚肉巻き中華風', genre: '中', time: 20, need: ['pork', 'mushroom', 'negi', 'soy_sauce', 'sesame_oil', 'katakuriko'] },
  { name: 'なすと豚肉の中華炒め', genre: '中', time: 20, need: ['nasu', 'pork', 'doubanjiang', 'oyster_sauce', 'garlic'] },
  { name: '豆腐と卵の中華スープ炒め', genre: '中', time: 20, need: ['tofu', 'egg', 'chuka_dashi', 'katakuriko', 'negi'] },

  // ===== 洋食 30品 =====
  { name: 'ハンバーグ', genre: '洋', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'milk', 'ketchup', 'worcester', 'salt', 'pepper'] },
  { name: 'カレーライス', genre: '洋', time: 45, need: ['pork', 'onion', 'carrot', 'potato', 'curry_roux', 'rice'] },
  { name: 'オムライス', genre: '洋', time: 20, need: ['egg', 'chicken', 'onion', 'ketchup', 'rice', 'butter'] },
  { name: 'ナポリタン', genre: '洋', time: 20, need: ['pasta', 'sausage', 'piman', 'onion', 'mushroom', 'ketchup', 'butter'] },
  { name: 'ミートソースパスタ', genre: '洋', time: 30, need: ['pasta', 'mixed_mince', 'tomato_can', 'onion', 'garlic', 'olive_oil', 'consomme'] },
  { name: 'カルボナーラ', genre: '洋', time: 20, need: ['pasta', 'bacon', 'egg', 'cheese', 'cream', 'pepper'] },
  { name: 'クリームシチュー', genre: '洋', time: 45, need: ['chicken', 'onion', 'carrot', 'potato', 'milk', 'butter', 'flour', 'consomme'] },
  { name: 'ビーフシチュー', genre: '洋', time: 45, need: ['beef', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme', 'butter'] },
  { name: 'コロッケ', genre: '洋', time: 45, need: ['potato', 'mixed_mince', 'onion', 'panko', 'egg', 'flour', 'oil'] },
  { name: 'チキンソテー', genre: '洋', time: 20, need: ['chicken', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'] },
  { name: 'ポークソテー', genre: '洋', time: 20, need: ['pork', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'] },
  { name: 'ハヤシライス', genre: '洋', time: 30, need: ['beef', 'onion', 'tomato_can', 'ketchup', 'consomme', 'butter', 'rice'] },
  { name: 'ロールキャベツ', genre: '洋', time: 45, need: ['cabbage', 'mixed_mince', 'onion', 'consomme', 'tomato_can'] },
  { name: 'グラタン', genre: '洋', time: 30, need: ['chicken', 'onion', 'mushroom', 'milk', 'butter', 'flour', 'cheese', 'panko'] },
  { name: 'ドリア', genre: '洋', time: 30, need: ['rice', 'chicken', 'onion', 'milk', 'butter', 'flour', 'cheese', 'ketchup'] },
  { name: 'フライドチキン', genre: '洋', time: 30, need: ['chicken', 'flour', 'egg', 'panko', 'salt', 'pepper', 'oil'] },
  { name: 'ポトフ', genre: '洋', time: 30, need: ['sausage', 'cabbage', 'carrot', 'potato', 'onion', 'consomme'] },
  { name: 'トマトとチーズのオムレツ', genre: '洋', time: 10, need: ['egg', 'tomato', 'cheese', 'milk', 'salt', 'pepper', 'butter'] },
  { name: 'ツナとトマトのパスタ', genre: '洋', time: 20, need: ['pasta', 'tuna_can', 'tomato_can', 'garlic', 'olive_oil'] },
  { name: 'きのこのクリームパスタ', genre: '洋', time: 20, need: ['pasta', 'mushroom', 'bacon', 'cream', 'butter', 'consomme', 'cheese'] },
  { name: 'ペペロンチーノ', genre: '洋', time: 10, need: ['pasta', 'garlic', 'olive_oil', 'salt', 'pepper'] },
  { name: 'ジャーマンポテト', genre: '洋', time: 20, need: ['potato', 'sausage', 'onion', 'butter', 'salt', 'pepper'] },
  { name: 'きのこのアヒージョ', genre: '洋', time: 10, need: ['mushroom', 'garlic', 'olive_oil', 'salt', 'pepper'] },
  { name: 'キッシュ', genre: '洋', time: 45, need: ['egg', 'bacon', 'onion', 'cheese', 'cream', 'flour', 'butter'] },
  { name: 'ラザニア', genre: '洋', time: 45, need: ['pasta', 'mixed_mince', 'tomato_can', 'cheese', 'milk', 'flour', 'butter'] },
  { name: 'チーズハンバーグ', genre: '洋', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'cheese', 'ketchup'] },
  { name: 'ビーフストロガノフ', genre: '洋', time: 30, need: ['beef', 'onion', 'mushroom', 'cream', 'consomme', 'butter'] },
  { name: 'ミネストローネ風煮込み', genre: '洋', time: 30, need: ['bacon', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme'] },
  { name: 'ツナグラタン', genre: '洋', time: 30, need: ['tuna_can', 'onion', 'milk', 'butter', 'flour', 'cheese', 'panko'] },
  { name: 'ウインナーのケチャップ炒め', genre: '洋', time: 10, need: ['sausage', 'piman', 'onion', 'ketchup'] },

  // ===== 他 10品 =====
  { name: 'ガパオライス', genre: '他', time: 20, need: ['pork_mince', 'piman', 'onion', 'garlic', 'oyster_sauce', 'soy_sauce', 'sugar', 'egg', 'rice'] },
  { name: 'ビビンバ', genre: '他', time: 30, need: ['beef', 'moyashi', 'carrot', 'spinach_frozen', 'egg', 'soy_sauce', 'sesame_oil', 'garlic', 'rice'] },
  { name: 'プルコギ', genre: '他', time: 20, need: ['beef', 'onion', 'negi', 'soy_sauce', 'sugar', 'sesame_oil', 'garlic'] },
  { name: 'タコライス', genre: '他', time: 20, need: ['mixed_mince', 'cheese', 'tomato', 'lettuce', 'ketchup', 'consomme', 'rice'] },
  { name: 'チリコンカン', genre: '他', time: 45, need: ['mixed_mince', 'tomato_can', 'onion', 'garlic', 'consomme'] },
  { name: 'ヤンニョムチキン', genre: '他', time: 30, need: ['chicken', 'ketchup', 'garlic', 'sugar', 'soy_sauce', 'oil'] },
  { name: 'カオマンガイ', genre: '他', time: 30, need: ['chicken', 'rice', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil'] },
  { name: 'エスニック風鶏肉炒め', genre: '他', time: 20, need: ['chicken', 'piman', 'onion', 'oyster_sauce', 'garlic', 'sesame_oil'] },
  { name: 'アジアン風豚肉と野菜の炒め物', genre: '他', time: 20, need: ['pork', 'cabbage', 'carrot', 'oyster_sauce', 'garlic', 'sesame_oil'] },
  { name: 'カレー風味の卵と厚揚げ炒め', genre: '他', time: 10, need: ['egg', 'atsuage', 'curry_roux', 'onion', 'soy_sauce'] },
];
