'use strict';

// 保有食材のカテゴリ定義（キー: 食材ID, 値: 表示名）
const INGREDIENT_CATEGORIES = [
  {
    key: 'meat',
    label: '肉類',
    items: [
      ['pork', '豚肉'],
      ['chicken', '鶏肉'],
      ['beef', '牛肉'],
      ['chicken_mince', '鶏ひき肉'],
      ['pork_mince', '豚ひき肉'],
      ['mixed_mince', '合いびき肉'],
      ['bacon', 'ベーコン'],
      ['sausage', 'ウインナー'],
    ],
  },
  {
    key: 'egg_tofu',
    label: '卵・豆腐',
    items: [
      ['egg', '卵'],
      ['tofu', '豆腐'],
      ['atsuage', '厚揚げ'],
      ['natto', '納豆'],
    ],
  },
  {
    key: 'vegetable',
    label: '野菜（生・冷凍）',
    items: [
      ['onion', '玉ねぎ'],
      ['carrot', 'にんじん'],
      ['cabbage', 'キャベツ'],
      ['potato', 'じゃがいも'],
      ['nasu', 'なす'],
      ['tomato', 'トマト'],
      ['minitomato', 'ミニトマト'],
      ['cucumber', 'きゅうり'],
      ['piman', 'ピーマン'],
      ['moyashi', 'もやし'],
      ['negi', '長ねぎ'],
      ['garlic', 'にんにく'],
      ['ginger', 'しょうが'],
      ['mushroom', 'きのこ類'],
      ['daikon', '大根'],
      ['lettuce', 'レタス'],
      ['spinach_frozen', 'ほうれん草（冷凍）'],
      ['broccoli_frozen', 'ブロッコリー（冷凍）'],
      ['corn_frozen', 'コーン（冷凍）'],
    ],
  },
  {
    key: 'dried_can',
    label: '乾物・缶詰',
    items: [
      ['harusame', '春雨'],
      ['tuna_can', 'ツナ缶'],
      ['tomato_can', 'トマト缶'],
      ['katakuriko', '片栗粉'],
      ['rice', '米'],
      ['pasta', 'パスタ'],
      ['udon', 'うどん'],
      ['chuka_men', '中華麺'],
      ['panko', 'パン粉'],
      ['flour', '小麦粉'],
      ['hijiki', 'ひじき'],
      ['kiriboshi_daikon', '切り干し大根'],
    ],
  },
  {
    key: 'dairy',
    label: '乳製品',
    items: [
      ['cheese', 'チーズ'],
      ['milk', '牛乳'],
      ['butter', 'バター'],
      ['cream', '生クリーム'],
      ['yogurt', 'ヨーグルト'],
    ],
  },
];

// 調味料タブ定義
const SEASONING_TABS = [
  {
    key: 'japanese',
    label: '和',
    items: [
      ['soy_sauce', '醤油'],
      ['miso', '味噌'],
      ['mirin', 'みりん'],
      ['sake', '酒'],
      ['sugar', '砂糖'],
      ['dashi', 'だし'],
      ['vinegar', '酢'],
      ['mentsuyu', 'めんつゆ'],
    ],
  },
  {
    key: 'western',
    label: '洋',
    items: [
      ['salt', '塩'],
      ['pepper', 'こしょう'],
      ['olive_oil', 'オリーブオイル'],
      ['consomme', 'コンソメ'],
      ['ketchup', 'ケチャップ'],
      ['mayo', 'マヨネーズ'],
      ['worcester', 'ウスターソース'],
    ],
  },
  {
    key: 'chinese',
    label: '中',
    items: [
      ['oyster_sauce', 'オイスターソース'],
      ['doubanjiang', '豆板醤'],
      ['sesame_oil', 'ごま油'],
      ['chuka_dashi', '中華だし'],
      ['tenmenjan', '甜麺醤'],
    ],
  },
  {
    key: 'other',
    label: 'その他',
    items: [
      ['curry_roux', 'カレールー'],
      ['oil', '油'],
      ['ponzu', 'ポン酢'],
      ['dashi_soy', 'だし醤油'],
    ],
  },
];

// 1人前あたりの目安量（食材ID -> 分量）。fixed のものは人数によらず一定量を表示する
const INGREDIENT_SERVING_INFO = {
  pork: { amount: 100, unit: 'g' },
  chicken: { amount: 100, unit: 'g' },
  beef: { amount: 100, unit: 'g' },
  chicken_mince: { amount: 80, unit: 'g' },
  pork_mince: { amount: 80, unit: 'g' },
  mixed_mince: { amount: 80, unit: 'g' },
  bacon: { amount: 1, unit: '枚' },
  sausage: { amount: 1.5, unit: '本' },
  egg: { amount: 1, unit: '個' },
  tofu: { amount: 0.5, unit: '丁' },
  atsuage: { amount: 0.5, unit: '枚' },
  natto: { amount: 1, unit: 'パック' },
  onion: { amount: 0.5, unit: '個' },
  carrot: { amount: 0.5, unit: '本' },
  cabbage: { amount: 100, unit: 'g' },
  potato: { amount: 1, unit: '個' },
  nasu: { amount: 1, unit: '本' },
  tomato: { amount: 0.5, unit: '個' },
  minitomato: { amount: 4, unit: '個' },
  cucumber: { amount: 0.5, unit: '本' },
  piman: { amount: 1, unit: '個' },
  moyashi: { amount: 0.5, unit: '袋' },
  negi: { amount: 0.5, unit: '本' },
  garlic: { amount: 1, unit: '片' },
  ginger: { amount: 1, unit: '片' },
  mushroom: { amount: 50, unit: 'g' },
  daikon: { amount: 100, unit: 'g' },
  lettuce: { amount: 2, unit: '枚' },
  spinach_frozen: { amount: 50, unit: 'g' },
  broccoli_frozen: { amount: 50, unit: 'g' },
  corn_frozen: { amount: 30, unit: 'g' },
  harusame: { amount: 20, unit: 'g' },
  tuna_can: { amount: 0.5, unit: '缶' },
  tomato_can: { amount: 0.5, unit: '缶' },
  katakuriko: { amount: 1, unit: '小さじ' },
  rice: { amount: 0.5, unit: '合' },
  pasta: { amount: 100, unit: 'g' },
  udon: { amount: 1, unit: '玉' },
  chuka_men: { amount: 1, unit: '玉' },
  panko: { amount: 2, unit: '大さじ' },
  flour: { amount: 2, unit: '大さじ' },
  hijiki: { amount: 5, unit: 'g' },
  kiriboshi_daikon: { amount: 15, unit: 'g' },
  cheese: { amount: 20, unit: 'g' },
  milk: { amount: 50, unit: 'ml' },
  butter: { amount: 10, unit: 'g' },
  cream: { amount: 50, unit: 'ml' },
  yogurt: { amount: 50, unit: 'g' },
  soy_sauce: { amount: 0.5, unit: '大さじ' },
  miso: { amount: 0.5, unit: '大さじ' },
  mirin: { amount: 0.5, unit: '大さじ' },
  sake: { amount: 0.5, unit: '大さじ' },
  sugar: { amount: 1, unit: '小さじ' },
  dashi: { amount: 100, unit: 'ml' },
  vinegar: { amount: 1, unit: '小さじ' },
  mentsuyu: { amount: 0.5, unit: '大さじ' },
  salt: { fixed: '少々' },
  pepper: { fixed: '少々' },
  olive_oil: { amount: 0.5, unit: '大さじ' },
  consomme: { amount: 1, unit: '小さじ' },
  ketchup: { amount: 1, unit: '大さじ' },
  mayo: { amount: 1, unit: '大さじ' },
  worcester: { amount: 1, unit: '小さじ' },
  oyster_sauce: { amount: 1, unit: '小さじ' },
  doubanjiang: { amount: 0.5, unit: '小さじ' },
  sesame_oil: { amount: 1, unit: '小さじ' },
  chuka_dashi: { amount: 0.5, unit: '小さじ' },
  tenmenjan: { amount: 1, unit: '小さじ' },
  curry_roux: { amount: 1, unit: 'かけ' },
  oil: { amount: 1, unit: '大さじ' },
  ponzu: { amount: 1, unit: '大さじ' },
  dashi_soy: { amount: 0.5, unit: '大さじ' },
};

// 料理データベース（100品: 和30 / 中30 / 洋30 / 他10）
const DISHES = [
  // ===== 和食 30品 =====
  { name: '肉じゃが', genre: '和', time: 30, need: ['pork', 'onion', 'potato', 'carrot', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['豚肉と野菜を一口大に切る。', '鍋で豚肉を炒め、色が変わったら玉ねぎ・にんじん・じゃがいもを加えてさらに炒める。', 'だし汁を加えて煮立たせ、アクを取りながら弱火で10分煮る。', '醤油・みりん・砂糖を加え、じゃがいもが柔らかくなるまで煮含める。'] },
  { name: '豚の生姜焼き', genre: '和', time: 20, need: ['pork', 'onion', 'ginger', 'soy_sauce', 'mirin', 'sugar'], steps: ['豚肉に軽く塩こしょうし、玉ねぎを薄切りにする。', 'しょうが・醤油・みりん・砂糖を混ぜてタレを作る。', 'フライパンで玉ねぎと豚肉を炒め、火が通ったらタレを絡めて仕上げる。'] },
  { name: '鶏の照り焼き', genre: '和', time: 20, need: ['chicken', 'soy_sauce', 'mirin', 'sugar', 'sake'], steps: ['鶏肉に切り込みを入れ、皮目から焼く。', '両面に焼き色がついたら余分な油を拭き取る。', '醤油・みりん・砂糖・酒を加え、とろみがつくまで煮絡める。'] },
  { name: '肉豆腐', genre: '和', time: 20, need: ['beef', 'tofu', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['豆腐は一口大、長ねぎは斜め切りにする。', '鍋にだし・醤油・みりん・砂糖を煮立て、牛肉を加えて煮る。', '豆腐と長ねぎを加え、味がなじむまで煮る。'] },
  { name: '豚汁', genre: '和', time: 30, need: ['pork', 'daikon', 'carrot', 'negi', 'miso', 'dashi'], steps: ['豚肉と大根・にんじんを一口大に切る。', '鍋で豚肉を炒め、大根・にんじん・長ねぎを加えて炒める。', 'だしを加えて煮込み、野菜が柔らかくなったら味噌を溶き入れる。'] },
  { name: '筑前煮', genre: '和', time: 45, need: ['chicken', 'carrot', 'daikon', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['鶏肉・にんじん・大根・きのこを一口大に切る。', '鍋で鶏肉を炒め、野菜を加えてさらに炒める。', 'だしを加えて煮立て、醤油・みりん・砂糖を加えて弱火でコトコト煮含める。'] },
  { name: '肉巻き野菜', genre: '和', time: 20, need: ['pork', 'carrot', 'piman', 'soy_sauce', 'mirin', 'sugar'], steps: ['にんじん・ピーマンを細切りにし、豚肉で巻く。', '巻き終わりを下にしてフライパンで焼き、全面に焼き色をつける。', '醤油・みりん・砂糖を加えて煮絡める。'] },
  { name: '親子丼', genre: '和', time: 20, need: ['chicken', 'egg', 'onion', 'soy_sauce', 'mirin', 'sugar', 'dashi', 'rice'], steps: ['鶏肉と玉ねぎを一口大に切る。', 'だし・醤油・みりん・砂糖を煮立て、鶏肉と玉ねぎを煮る。', '溶き卵を回し入れ、半熟になったらご飯にのせる。'] },
  { name: 'だし巻き卵', genre: '和', time: 10, need: ['egg', 'soy_sauce', 'sugar', 'dashi'], steps: ['卵にだし・醤油・砂糖を混ぜる。', '卵焼き器を温め、卵液を数回に分けて流し入れながら巻く。', '形を整えて焼き上げ、食べやすい大きさに切る。'] },
  { name: '豆腐ハンバーグ', genre: '和', time: 30, need: ['tofu', 'mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce'], steps: ['豆腐は水切りし、玉ねぎはみじん切りにして炒める。', '合いびき肉・豆腐・卵・パン粉・炒めた玉ねぎを混ぜて成形する。', 'フライパンで両面を焼き、中まで火を通す。', '醤油ベースのタレをかけて仕上げる。'] },
  { name: 'すき焼き風煮', genre: '和', time: 30, need: ['beef', 'tofu', 'negi', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'sake'], steps: ['長ねぎ・きのこを食べやすく切る。', '鍋に醤油・みりん・砂糖・酒を煮立て、牛肉をさっと煮る。', '豆腐・長ねぎ・きのこを加えて煮含める。'] },
  { name: '豚しゃぶサラダ', genre: '和', time: 20, need: ['pork', 'lettuce', 'cucumber', 'ponzu'], steps: ['豚肉を熱湯でさっと茹でて冷ます。', 'レタス・きゅうりを食べやすく切って皿に盛る。', '豚肉をのせてポン酢をかける。'] },
  { name: '鶏そぼろ丼', genre: '和', time: 20, need: ['chicken_mince', 'egg', 'soy_sauce', 'mirin', 'sugar', 'rice'], steps: ['鍋に鶏ひき肉・醤油・みりん・砂糖を入れ、ほぐしながら炒り煮する。', '別鍋で炒り卵を作る。', 'ご飯にそぼろと炒り卵を盛りつける。'] },
  { name: '厚揚げの煮物', genre: '和', time: 20, need: ['atsuage', 'daikon', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['厚揚げは食べやすく切り、大根は薄いいちょう切りにする。', '鍋にだし・醤油・みりん・砂糖を煮立て、大根と厚揚げを加える。', '弱火で煮含め、長ねぎを加えてひと煮立ちさせる。'] },
  { name: '豚バラ大根', genre: '和', time: 45, need: ['pork', 'daikon', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['大根は厚めの半月切りにし、下茹でしておく。', '豚バラ肉を炒め、大根を加えてさらに炒める。', 'だし・醤油・みりん・砂糖を加え、大根が柔らかくなるまで煮込む。'] },
  { name: '鶏の唐揚げ', genre: '和', time: 20, need: ['chicken', 'soy_sauce', 'sake', 'ginger', 'garlic', 'katakuriko', 'oil'], steps: ['鶏肉を一口大に切り、醤油・酒・しょうが・にんにくに漬け込む。', '汁気を軽く切り、片栗粉をまぶす。', '170℃の油できつね色になるまで揚げる。'] },
  { name: 'じゃがいもの煮っころがし', genre: '和', time: 20, need: ['potato', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['じゃがいもを一口大に切る。', '鍋で軽く炒め、だし・醤油・みりん・砂糖を加える。', '落し蓋をして煮汁が少なくなるまで転がしながら煮る。'] },
  { name: 'なすの煮浸し', genre: '和', time: 20, need: ['nasu', 'dashi', 'soy_sauce', 'mirin'], steps: ['なすを乱切りにし、油でさっと炒める。', 'だし・醤油・みりんを煮立て、なすを加える。', '味を含ませながら煮て、冷ましても美味しい。'] },
  { name: 'ひじきの煮物', genre: '和', time: 30, need: ['hijiki', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['ひじきを水で戻し、にんじんは細切りにする。', '鍋で油ひじき・にんじん・厚揚げを炒める。', 'だし・醤油・みりん・砂糖を加え、汁気がなくなるまで煮る。'] },
  { name: '切り干し大根の煮物', genre: '和', time: 30, need: ['kiriboshi_daikon', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['切り干し大根を水で戻し、水気を絞る。', 'にんじん・厚揚げと一緒に油で炒める。', 'だし・醤油・みりん・砂糖を加えて煮含める。'] },
  { name: '豚しゃぶ鍋', genre: '和', time: 30, need: ['pork', 'cabbage', 'negi', 'mushroom', 'tofu', 'dashi', 'soy_sauce'], steps: ['キャベツ・長ねぎ・きのこ・豆腐を食べやすく切る。', '鍋にだしと醤油を入れて煮立てる。', '野菜を煮ながら豚肉をしゃぶしゃぶして食べる。'] },
  { name: '焼き鳥丼', genre: '和', time: 20, need: ['chicken', 'negi', 'soy_sauce', 'mirin', 'sugar', 'sake', 'rice'], steps: ['鶏肉と長ねぎを一口大に切る。', 'フライパンで焼き色をつけながら焼く。', '醤油・みりん・砂糖・酒のタレを絡め、ご飯にのせる。'] },
  { name: '和風ハンバーグ', genre: '和', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce', 'mirin', 'sugar', 'daikon'], steps: ['玉ねぎをみじん切りにして炒め、冷ましておく。', '合いびき肉・卵・パン粉・玉ねぎを混ぜて成形し、焼く。', '大根おろしと醤油・みりん・砂糖のタレをかける。'] },
  { name: '卵とじうどん', genre: '和', time: 20, need: ['udon', 'egg', 'negi', 'dashi', 'soy_sauce', 'mirin'], steps: ['うどんを表示通りに茹でる。', 'だし・醤油・みりんを煮立て、長ねぎを加える。', 'うどんを加えて温め、溶き卵を回し入れてとじる。'] },
  { name: '肉うどん', genre: '和', time: 20, need: ['udon', 'beef', 'negi', 'dashi', 'soy_sauce', 'mirin', 'sugar'], steps: ['うどんを表示通りに茹でる。', 'だし・醤油・みりん・砂糖を煮立て、牛肉と長ねぎを煮る。', '器にうどんを盛り、煮た具と汁をかける。'] },
  { name: '豚の味噌漬け焼き', genre: '和', time: 20, need: ['pork', 'miso', 'mirin', 'sugar', 'sake'], steps: ['味噌・みりん・砂糖・酒を混ぜて豚肉に漬け込む。', '味噌を軽く拭き取り、焦げないよう弱めの火で焼く。', '中まで火が通ったら切り分ける。'] },
  { name: '厚揚げの照り焼き', genre: '和', time: 20, need: ['atsuage', 'negi', 'soy_sauce', 'mirin', 'sugar', 'katakuriko'], steps: ['厚揚げを一口大に切り、片栗粉を薄くまぶす。', 'フライパンで焼き色がつくまで焼く。', '醤油・みりん・砂糖のタレを絡め、長ねぎを散らす。'] },
  { name: '鶏むね肉のマヨポン炒め', genre: '和', time: 20, need: ['chicken', 'mayo', 'ponzu', 'negi'], steps: ['鶏むね肉を一口大に切る。', 'フライパンで焼き、火が通ったら長ねぎを加える。', 'マヨネーズとポン酢を加えて絡める。'] },
  { name: '豚肉と白菜風煮浸し', genre: '和', time: 20, need: ['pork', 'cabbage', 'dashi', 'soy_sauce', 'mirin'], steps: ['キャベツはざく切り、豚肉は食べやすく切る。', '鍋でさっと炒め、だし・醤油・みりんを加える。', '蓋をして柔らかくなるまで煮浸しにする。'] },
  { name: '冷奴', genre: '和', time: 10, need: ['tofu', 'negi', 'soy_sauce'], steps: ['豆腐を食べやすく切って器に盛る。', '長ねぎを小口切りにしてのせる。', '醤油をかけて完成。'] },

  // ===== 中華 30品 =====
  { name: '麻婆豆腐', genre: '中', time: 20, need: ['tofu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'ginger', 'katakuriko', 'chuka_dashi'], steps: ['豆腐は角切りにし、湯通ししておく。', '豚ひき肉・にんにく・しょうがを炒め、豆板醤を加えて香りを出す。', '中華だし・醤油・砂糖を加えて煮立て、豆腐を加える。', '水溶き片栗粉でとろみをつける。'] },
  { name: '青椒肉絲', genre: '中', time: 20, need: ['beef', 'piman', 'oyster_sauce', 'soy_sauce', 'sugar', 'katakuriko', 'garlic'], steps: ['牛肉とピーマンを細切りにする。', '牛肉に片栗粉をまぶして炒める。', 'ピーマン・にんにくを加えて炒め、オイスターソース・醤油・砂糖で味付けする。'] },
  { name: '回鍋肉', genre: '中', time: 20, need: ['pork', 'cabbage', 'doubanjiang', 'miso', 'sugar', 'garlic'], steps: ['豚肉とキャベツを一口大に切る。', 'にんにくを炒めて香りを出し、豚肉を炒める。', 'キャベツを加えて炒め、豆板醤・味噌・砂糖で味付けする。'] },
  { name: '酢豚', genre: '中', time: 30, need: ['pork', 'piman', 'onion', 'carrot', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'katakuriko'], steps: ['豚肉に片栗粉をまぶして揚げ焼きにする。', '玉ねぎ・にんじん・ピーマンを炒める。', 'ケチャップ・酢・砂糖・醤油を混ぜたタレを加え、豚肉を戻して絡める。'] },
  { name: '餃子', genre: '中', time: 45, need: ['pork_mince', 'cabbage', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'katakuriko'], steps: ['キャベツをみじん切りにして塩もみし、水気を絞る。', '豚ひき肉・キャベツ・にんにく・しょうが・醤油・ごま油を混ぜて餡を作る。', '皮に包み、フライパンで焼いて蒸し焼きにする。'] },
  { name: '春巻き', genre: '中', time: 30, need: ['pork_mince', 'harusame', 'carrot', 'cabbage', 'oyster_sauce', 'sesame_oil'], steps: ['春雨は戻して切り、にんじん・キャベツは細切りにする。', '豚ひき肉と野菜をオイスターソース・ごま油で炒めて具を作る。', '皮で包み、油で揚げる。'] },
  { name: '中華丼', genre: '中', time: 20, need: ['pork', 'cabbage', 'carrot', 'mushroom', 'oyster_sauce', 'chuka_dashi', 'katakuriko', 'rice'], steps: ['豚肉・キャベツ・にんじん・きのこを一口大に切る。', '炒めて中華だし・オイスターソースで味付けする。', '水溶き片栗粉でとろみをつけ、ご飯にかける。'] },
  { name: '麻婆春雨', genre: '中', time: 20, need: ['pork_mince', 'harusame', 'doubanjiang', 'soy_sauce', 'garlic', 'chuka_dashi'], steps: ['春雨は熱湯で戻しておく。', '豚ひき肉・にんにくを炒め、豆板醤を加える。', '中華だし・醤油と春雨を加えて汁気を吸わせるように煮る。'] },
  { name: '天津飯', genre: '中', time: 20, need: ['egg', 'tuna_can', 'katakuriko', 'chuka_dashi', 'soy_sauce', 'rice'], steps: ['卵にツナを混ぜて溶いておく。', 'フライパンで半熟に焼き、ご飯にのせる。', '中華だし・醤油・水溶き片栗粉であんを作りかける。'] },
  { name: '棒々鶏', genre: '中', time: 20, need: ['chicken', 'cucumber', 'sesame_oil', 'soy_sauce', 'sugar', 'vinegar'], steps: ['鶏肉を茹でて冷まし、手で細かく裂く。', 'きゅうりを細切りにして皿に盛る。', '醤油・砂糖・酢・ごま油を混ぜたタレをかける。'] },
  { name: 'よだれ鶏', genre: '中', time: 20, need: ['chicken', 'negi', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'vinegar'], steps: ['鶏肉を茹でて冷まし、食べやすく切る。', 'にんにく・しょうがをみじん切りにする。', '醤油・酢・ごま油・にんにく・しょうがを混ぜたタレをかける。'] },
  { name: '鶏の甘酢あん', genre: '中', time: 20, need: ['chicken', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce'], steps: ['鶏肉に片栗粉をまぶして揚げ焼きにする。', 'ケチャップ・酢・砂糖・醤油を煮立ててタレを作る。', '鶏肉にタレを絡める。'] },
  { name: '豚肉と厚揚げの中華炒め', genre: '中', time: 20, need: ['pork', 'atsuage', 'negi', 'oyster_sauce', 'garlic'], steps: ['豚肉と厚揚げを一口大に切る。', 'にんにくを炒めて香りを出し、豚肉を炒める。', '厚揚げと長ねぎを加え、オイスターソースで味付けする。'] },
  { name: 'もやし玉子炒め', genre: '中', time: 10, need: ['egg', 'moyashi', 'negi', 'sesame_oil', 'salt', 'pepper'], steps: ['もやしをさっと洗い、長ねぎを小口切りにする。', '卵を溶いてごま油で炒め、半熟で取り出す。', 'もやしと長ねぎを炒め、卵を戻して塩こしょうで味を調える。'] },
  { name: '豚肉と白菜の中華煮込み', genre: '中', time: 20, need: ['pork', 'cabbage', 'mushroom', 'chuka_dashi', 'oyster_sauce', 'katakuriko'], steps: ['豚肉とキャベツ・きのこを食べやすく切る。', '炒めてから中華だしを加えて煮る。', 'オイスターソースと水溶き片栗粉でとろみをつける。'] },
  { name: '麻婆なす', genre: '中', time: 20, need: ['nasu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'katakuriko'], steps: ['なすを乱切りにして炒める。', '豚ひき肉・にんにくを炒め、豆板醤を加える。', 'なすを戻し、醤油・砂糖と水溶き片栗粉でとろみをつける。'] },
  { name: '担々麺', genre: '中', time: 20, need: ['chuka_men', 'pork_mince', 'doubanjiang', 'sesame_oil', 'chuka_dashi', 'miso'], steps: ['中華麺を表示通りに茹でる。', '豚ひき肉・豆板醤を炒め、味噌・中華だしで肉味噌を作る。', 'ごま油を加えたスープに麺を入れ、肉味噌をのせる。'] },
  { name: 'ジャージャー麺', genre: '中', time: 20, need: ['chuka_men', 'pork_mince', 'tenmenjan', 'miso', 'garlic', 'katakuriko'], steps: ['中華麺を茹でておく。', '豚ひき肉・にんにくを炒め、甜麺醤・味噌で肉味噌を作る。', '水溶き片栗粉でとろみをつけ、麺にのせる。'] },
  { name: '八宝菜', genre: '中', time: 45, need: ['pork', 'cabbage', 'carrot', 'mushroom', 'moyashi', 'chuka_dashi', 'katakuriko', 'oyster_sauce'], steps: ['豚肉・キャベツ・にんじん・きのこ・もやしを食べやすく切る。', '豚肉から炒め、野菜を加えてさらに炒める。', '中華だし・オイスターソースを加え、水溶き片栗粉でとろみをつける。'] },
  { name: '肉団子の甘酢あん', genre: '中', time: 30, need: ['mixed_mince', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'egg'], steps: ['合いびき肉に片栗粉・卵を混ぜて団子状に丸め、揚げ焼きにする。', 'ケチャップ・酢・砂糖・醤油でタレを作る。', '団子にタレを絡める。'] },
  { name: '中華風炒り豆腐', genre: '中', time: 20, need: ['tofu', 'egg', 'negi', 'oyster_sauce', 'sesame_oil'], steps: ['豆腐を崩して水気を切る。', 'ごま油で豆腐と長ねぎを炒める。', '溶き卵を加え、オイスターソースで味付けする。'] },
  { name: 'ブロッコリー炒め', genre: '中', time: 10, need: ['broccoli_frozen', 'garlic', 'oyster_sauce', 'sesame_oil'], steps: ['ブロッコリーは解凍しておく。', 'にんにくをごま油で炒めて香りを出す。', 'ブロッコリーを加えて炒め、オイスターソースで味付けする。'] },
  { name: 'もやしと豚肉の中華炒め', genre: '中', time: 20, need: ['pork', 'moyashi', 'negi', 'oyster_sauce', 'sesame_oil', 'garlic'], steps: ['豚肉ともやし・長ねぎを用意する。', 'にんにくを炒めて豚肉を加える。', 'もやし・長ねぎを加えて炒め、オイスターソース・ごま油で味付けする。'] },
  { name: 'あんかけ焼きそば', genre: '中', time: 30, need: ['chuka_men', 'pork', 'cabbage', 'carrot', 'mushroom', 'chuka_dashi', 'katakuriko', 'oyster_sauce'], steps: ['中華麺を焼いてカリッとさせる。', '豚肉・キャベツ・にんじん・きのこを炒める。', '中華だし・オイスターソースを加え、水溶き片栗粉でとろみをつけて麺にかける。'] },
  { name: '鶏肉と厚揚げの中華煮', genre: '中', time: 30, need: ['chicken', 'atsuage', 'negi', 'chuka_dashi', 'oyster_sauce', 'katakuriko'], steps: ['鶏肉と厚揚げを一口大に切る。', '炒めてから中華だしを加えて煮る。', 'オイスターソースと水溶き片栗粉でとろみをつける。'] },
  { name: '豚バラともやしのレンジ蒸し', genre: '中', time: 20, need: ['pork', 'moyashi', 'negi', 'sesame_oil', 'salt'], steps: ['もやしを耐熱皿に敷き、豚肉をのせる。', '塩・ごま油をふり、ラップをして電子レンジで加熱する。', '長ねぎを散らして完成。'] },
  { name: '卵とツナの中華炒め', genre: '中', time: 10, need: ['egg', 'tuna_can', 'negi', 'sesame_oil', 'oyster_sauce'], steps: ['ツナ缶の油を軽く切る。', '卵を溶いてごま油で半熟に炒める。', 'ツナと長ねぎを加え、オイスターソースで味付けする。'] },
  { name: 'えのきの豚肉巻き中華風', genre: '中', time: 20, need: ['pork', 'mushroom', 'negi', 'soy_sauce', 'sesame_oil', 'katakuriko'], steps: ['きのこを豚肉で巻く。', 'フライパンで転がしながら焼き、火を通す。', '醤油・ごま油・水溶き片栗粉のタレを絡める。'] },
  { name: 'なすと豚肉の中華炒め', genre: '中', time: 20, need: ['nasu', 'pork', 'doubanjiang', 'oyster_sauce', 'garlic'], steps: ['なすを乱切りにし、豚肉と炒める。', 'にんにく・豆板醤を加えて香りを出す。', 'オイスターソースで味付けする。'] },
  { name: '豆腐と卵の中華スープ炒め', genre: '中', time: 20, need: ['tofu', 'egg', 'chuka_dashi', 'katakuriko', 'negi'], steps: ['豆腐を崩し、長ねぎを小口切りにする。', '中華だしで煮立て、豆腐を加える。', '溶き卵を回し入れ、水溶き片栗粉でとろみをつける。'] },

  // ===== 洋食 30品 =====
  { name: 'ハンバーグ', genre: '洋', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'milk', 'ketchup', 'worcester', 'salt', 'pepper'], steps: ['玉ねぎをみじん切りにして炒め、冷ます。', '合いびき肉・卵・パン粉・牛乳・玉ねぎ・塩こしょうを混ぜて成形する。', 'フライパンで両面を焼き、蓋をして中まで火を通す。', 'ケチャップ・ウスターソースでソースを作りかける。'] },
  { name: 'カレーライス', genre: '洋', time: 45, need: ['pork', 'onion', 'carrot', 'potato', 'curry_roux', 'rice'], steps: ['豚肉・玉ねぎ・にんじん・じゃがいもを一口大に切る。', '鍋で炒めてから水を加えて煮込む。', '火を止めてカレールーを溶かし、とろみがつくまで煮込む。'] },
  { name: 'オムライス', genre: '洋', time: 20, need: ['egg', 'chicken', 'onion', 'ketchup', 'rice', 'butter'], steps: ['鶏肉・玉ねぎを炒め、ご飯とケチャップを加えてチキンライスを作る。', '卵を溶いてバターで薄焼き卵を焼く。', 'チキンライスを包み、皿に盛る。'] },
  { name: 'ナポリタン', genre: '洋', time: 20, need: ['pasta', 'sausage', 'piman', 'onion', 'mushroom', 'ketchup', 'butter'], steps: ['パスタを表示通りに茹でる。', 'バターでウインナー・玉ねぎ・ピーマン・きのこを炒める。', '茹でたパスタとケチャップを加えて絡める。'] },
  { name: 'ミートソースパスタ', genre: '洋', time: 30, need: ['pasta', 'mixed_mince', 'tomato_can', 'onion', 'garlic', 'olive_oil', 'consomme'], steps: ['パスタを茹でる。', 'にんにく・玉ねぎを炒め、合いびき肉を加えて炒める。', 'トマト缶・コンソメを加えて煮込み、パスタに絡める。'] },
  { name: 'カルボナーラ', genre: '洋', time: 20, need: ['pasta', 'bacon', 'egg', 'cheese', 'cream', 'pepper'], steps: ['パスタを茹でる。', 'ベーコンを炒める。', '卵・チーズ・生クリーム・こしょうを混ぜたソースにパスタとベーコンを絡める。'] },
  { name: 'クリームシチュー', genre: '洋', time: 45, need: ['chicken', 'onion', 'carrot', 'potato', 'milk', 'butter', 'flour', 'consomme'], steps: ['鶏肉・玉ねぎ・にんじん・じゃがいもを一口大に切って炒める。', '水とコンソメを加えて煮込む。', 'バター・小麦粉を炒めたルーと牛乳を加え、とろみがつくまで煮る。'] },
  { name: 'ビーフシチュー', genre: '洋', time: 45, need: ['beef', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme', 'butter'], steps: ['牛肉・玉ねぎ・にんじん・じゃがいもを一口大に切って炒める。', 'トマト缶とコンソメ、水を加えて煮込む。', 'バターを加えて風味を整え、とろみが出るまで煮詰める。'] },
  { name: 'コロッケ', genre: '洋', time: 45, need: ['potato', 'mixed_mince', 'onion', 'panko', 'egg', 'flour', 'oil'], steps: ['じゃがいもを茹でて潰す。', '合いびき肉・玉ねぎを炒め、じゃがいもと混ぜて成形する。', '小麦粉・卵・パン粉の順につけ、油で揚げる。'] },
  { name: 'チキンソテー', genre: '洋', time: 20, need: ['chicken', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'], steps: ['鶏肉に塩こしょうする。', 'オリーブオイルとにんにくでフライパンを香りづけする。', '皮目からじっくり焼き、バターを絡めて仕上げる。'] },
  { name: 'ポークソテー', genre: '洋', time: 20, need: ['pork', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'], steps: ['豚肉に塩こしょうし、筋切りする。', 'オリーブオイルとにんにくで香りをつける。', '両面を焼き、バターを絡めて仕上げる。'] },
  { name: 'ハヤシライス', genre: '洋', time: 30, need: ['beef', 'onion', 'tomato_can', 'ketchup', 'consomme', 'butter', 'rice'], steps: ['牛肉・玉ねぎを炒める。', 'トマト缶・ケチャップ・コンソメを加えて煮込む。', 'バターでコクを出し、ご飯にかける。'] },
  { name: 'ロールキャベツ', genre: '洋', time: 45, need: ['cabbage', 'mixed_mince', 'onion', 'consomme', 'tomato_can'], steps: ['キャベツを柔らかく茹でる。', '合いびき肉・玉ねぎを混ぜてキャベツで巻く。', 'コンソメとトマト缶のスープで煮込む。'] },
  { name: 'グラタン', genre: '洋', time: 30, need: ['chicken', 'onion', 'mushroom', 'milk', 'butter', 'flour', 'cheese', 'panko'], steps: ['鶏肉・玉ねぎ・きのこを炒める。', 'バター・小麦粉・牛乳でホワイトソースを作り、具と合わせる。', '耐熱皿に入れチーズとパン粉をのせてオーブンで焼く。'] },
  { name: 'ドリア', genre: '洋', time: 30, need: ['rice', 'chicken', 'onion', 'milk', 'butter', 'flour', 'cheese', 'ketchup'], steps: ['ご飯にケチャップを混ぜて耐熱皿に敷く。', '鶏肉・玉ねぎを炒め、バター・小麦粉・牛乳でホワイトソースを作る。', 'ご飯にソースをかけ、チーズをのせて焼く。'] },
  { name: 'フライドチキン', genre: '洋', time: 30, need: ['chicken', 'flour', 'egg', 'panko', 'salt', 'pepper', 'oil'], steps: ['鶏肉に塩こしょうで下味をつける。', '小麦粉・卵・パン粉の順に衣をつける。', '油できつね色になるまで揚げる。'] },
  { name: 'ポトフ', genre: '洋', time: 30, need: ['sausage', 'cabbage', 'carrot', 'potato', 'onion', 'consomme'], steps: ['ウインナー・キャベツ・にんじん・じゃがいも・玉ねぎを大きめに切る。', '鍋に材料と水、コンソメを入れて煮込む。', '野菜が柔らかくなるまでじっくり煮る。'] },
  { name: 'トマトとチーズのオムレツ', genre: '洋', time: 10, need: ['egg', 'tomato', 'cheese', 'milk', 'salt', 'pepper', 'butter'], steps: ['トマトを角切りにする。', '卵に牛乳・塩こしょうを混ぜる。', 'バターで卵を焼き、トマトとチーズを包んで仕上げる。'] },
  { name: 'ツナとトマトのパスタ', genre: '洋', time: 20, need: ['pasta', 'tuna_can', 'tomato_can', 'garlic', 'olive_oil'], steps: ['パスタを茹でる。', 'にんにくをオリーブオイルで炒め、トマト缶とツナを加えて煮る。', 'パスタと絡める。'] },
  { name: 'きのこのクリームパスタ', genre: '洋', time: 20, need: ['pasta', 'mushroom', 'bacon', 'cream', 'butter', 'consomme', 'cheese'], steps: ['パスタを茹でる。', 'ベーコンときのこをバターで炒める。', '生クリーム・コンソメ・チーズを加えてソースを作り、パスタと絡める。'] },
  { name: 'ペペロンチーノ', genre: '洋', time: 10, need: ['pasta', 'garlic', 'olive_oil', 'salt', 'pepper'], steps: ['パスタを茹でる。', 'オリーブオイルでにんにくをじっくり熱して香りを出す。', '茹で汁少々とパスタを加えて塩こしょうで仕上げる。'] },
  { name: 'ジャーマンポテト', genre: '洋', time: 20, need: ['potato', 'sausage', 'onion', 'butter', 'salt', 'pepper'], steps: ['じゃがいもを一口大に切って下茹でする。', 'バターでウインナー・玉ねぎを炒める。', 'じゃがいもを加えて焼き色をつけ、塩こしょうで味を調える。'] },
  { name: 'きのこのアヒージョ', genre: '洋', time: 10, need: ['mushroom', 'garlic', 'olive_oil', 'salt', 'pepper'], steps: ['きのこを食べやすく切る。', 'オリーブオイルとにんにくを弱火で熱する。', 'きのこを加えて煮るように火を通し、塩こしょうで味を調える。'] },
  { name: 'キッシュ', genre: '洋', time: 45, need: ['egg', 'bacon', 'onion', 'cheese', 'cream', 'flour', 'butter'], steps: ['ベーコン・玉ねぎを炒める。', '卵・生クリーム・チーズを混ぜて具と合わせる。', '型に入れ、小麦粉を使った生地とともにオーブンで焼く。'] },
  { name: 'ラザニア', genre: '洋', time: 45, need: ['pasta', 'mixed_mince', 'tomato_can', 'cheese', 'milk', 'flour', 'butter'], steps: ['パスタ（ラザニア用）を茹でる。', '合いびき肉・トマト缶でミートソースを作る。', 'バター・小麦粉・牛乳でホワイトソースを作り、パスタと交互に重ねてチーズをのせて焼く。'] },
  { name: 'チーズハンバーグ', genre: '洋', time: 30, need: ['mixed_mince', 'egg', 'panko', 'onion', 'cheese', 'ketchup'], steps: ['玉ねぎをみじん切りにして炒める。', '合いびき肉・卵・パン粉・玉ねぎを混ぜ、チーズを包んで成形する。', '焼いてケチャップソースをかける。'] },
  { name: 'ビーフストロガノフ', genre: '洋', time: 30, need: ['beef', 'onion', 'mushroom', 'cream', 'consomme', 'butter'], steps: ['牛肉・玉ねぎ・きのこを炒める。', 'コンソメと水を加えて煮込む。', '生クリームとバターを加えてまろやかに仕上げる。'] },
  { name: 'ミネストローネ風煮込み', genre: '洋', time: 30, need: ['bacon', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme'], steps: ['ベーコン・玉ねぎ・にんじん・じゃがいもを炒める。', 'トマト缶と水、コンソメを加えて煮込む。', '野菜が柔らかくなるまで煮る。'] },
  { name: 'ツナグラタン', genre: '洋', time: 30, need: ['tuna_can', 'onion', 'milk', 'butter', 'flour', 'cheese', 'panko'], steps: ['玉ねぎを炒め、ツナを加える。', 'バター・小麦粉・牛乳でホワイトソースを作り、具と合わせる。', '耐熱皿に入れてチーズとパン粉をのせて焼く。'] },
  { name: 'ウインナーのケチャップ炒め', genre: '洋', time: 10, need: ['sausage', 'piman', 'onion', 'ketchup'], steps: ['ウインナーに切り込みを入れる。', '玉ねぎ・ピーマンとともに炒める。', 'ケチャップを加えて絡める。'] },

  // ===== 他 10品 =====
  { name: 'ガパオライス', genre: '他', time: 20, need: ['pork_mince', 'piman', 'onion', 'garlic', 'oyster_sauce', 'soy_sauce', 'sugar', 'egg', 'rice'], steps: ['にんにく・玉ねぎ・ピーマンを炒める。', 'ひき肉を加えて炒め、オイスターソース・醤油・砂糖で味付けする。', '目玉焼きをのせてご飯と一緒に盛る。'] },
  { name: 'ビビンバ', genre: '他', time: 30, need: ['beef', 'moyashi', 'carrot', 'spinach_frozen', 'egg', 'soy_sauce', 'sesame_oil', 'garlic', 'rice'], steps: ['牛肉を炒めて醤油・砂糖・ごま油・にんにくで味付けする。', 'もやし・にんじん・ほうれん草をそれぞれナムル風に和える。', 'ご飯に具材と卵をのせて盛りつける。'] },
  { name: 'プルコギ', genre: '他', time: 20, need: ['beef', 'onion', 'negi', 'soy_sauce', 'sugar', 'sesame_oil', 'garlic'], steps: ['牛肉を醤油・砂糖・ごま油・にんにくで下味をつける。', '玉ねぎ・長ねぎとともにフライパンで炒める。', '汁気が飛ぶまで炒めて仕上げる。'] },
  { name: 'タコライス', genre: '他', time: 20, need: ['mixed_mince', 'cheese', 'tomato', 'lettuce', 'ketchup', 'consomme', 'rice'], steps: ['合いびき肉を炒め、ケチャップとコンソメで味付けする。', 'ご飯の上に肉・レタス・トマト・チーズをのせる。'] },
  { name: 'チリコンカン', genre: '他', time: 45, need: ['mixed_mince', 'tomato_can', 'onion', 'garlic', 'consomme'], steps: ['合いびき肉・玉ねぎ・にんにくを炒める。', 'トマト缶とコンソメを加えて煮込む。', '汁気がなじむまでじっくり煮込む。'] },
  { name: 'ヤンニョムチキン', genre: '他', time: 30, need: ['chicken', 'ketchup', 'garlic', 'sugar', 'soy_sauce', 'oil'], steps: ['鶏肉を揚げ焼きにする。', 'ケチャップ・にんにく・砂糖・醤油を煮立ててタレを作る。', '鶏肉にタレを絡める。'] },
  { name: 'カオマンガイ', genre: '他', time: 30, need: ['chicken', 'rice', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil'], steps: ['米と鶏肉、にんにく・しょうがを一緒に炊く。', '鶏肉を取り出して食べやすく切る。', '醤油・ごま油のたれをかけてご飯と一緒に盛る。'] },
  { name: 'エスニック風鶏肉炒め', genre: '他', time: 20, need: ['chicken', 'piman', 'onion', 'oyster_sauce', 'garlic', 'sesame_oil'], steps: ['鶏肉とピーマン・玉ねぎを一口大に切る。', 'にんにくを炒めて香りを出し、鶏肉を加える。', 'ピーマン・玉ねぎを加え、オイスターソース・ごま油で味付けする。'] },
  { name: 'アジアン風豚肉と野菜の炒め物', genre: '他', time: 20, need: ['pork', 'cabbage', 'carrot', 'oyster_sauce', 'garlic', 'sesame_oil'], steps: ['豚肉とキャベツ・にんじんを食べやすく切る。', 'にんにくを炒めて豚肉を加える。', '野菜を加えて炒め、オイスターソース・ごま油で味付けする。'] },
  { name: 'カレー風味の卵と厚揚げ炒め', genre: '他', time: 10, need: ['egg', 'atsuage', 'curry_roux', 'onion', 'soy_sauce'], steps: ['厚揚げを一口大に切り、玉ねぎを薄切りにする。', 'フライパンで炒め、カレールーを少量溶かし入れる。', '溶き卵を加えて絡め、醤油で味を調える。'] },
];
