'use strict';

// 保有食材のカテゴリ定義（キー: 食材ID, 値: 表示名）
const INGREDIENT_CATEGORIES = [
  {
    key: 'meat',
    label: '肉類',
    items: [
      ['pork', '豚肉'],
      ['chicken', '鶏肉'],
      ['beef', '牛肉'],
      ['chicken_mince', '鶏ひき肉'],
      ['pork_mince', '豚ひき肉'],
      ['mixed_mince', '合いびき肉'],
      ['bacon', 'ベーコン'],
      ['sausage', 'ウインナー'],
    ],
  },
  {
    key: 'egg_tofu',
    label: '卵・豆腐',
    items: [
      ['egg', '卵'],
      ['tofu', '豆腐'],
      ['atsuage', '厚揚げ'],
      ['natto', '納豆'],
    ],
  },
  {
    key: 'vegetable',
    label: '野菜（生・冷凍）',
    items: [
      ['onion', '玉ねぎ'],
      ['carrot', 'にんじん'],
      ['cabbage', 'キャベツ'],
      ['potato', 'じゃがいも'],
      ['nasu', 'なす'],
      ['tomato', 'トマト'],
      ['minitomato', 'ミニトマト'],
      ['cucumber', 'きゅうり'],
      ['piman', 'ピーマン'],
      ['moyashi', 'もやし'],
      ['negi', '長ねぎ'],
      ['garlic', 'にんにく'],
      ['ginger', 'しょうが'],
      ['mushroom', 'きのこ類'],
      ['daikon', '大根'],
      ['lettuce', 'レタス'],
      ['spinach_frozen', 'ほうれん草（冷凍）'],
      ['broccoli_frozen', 'ブロッコリー（冷凍）'],
      ['corn_frozen', 'コーン（冷凍）'],
    ],
  },
  {
    key: 'dried_can',
    label: '乾物・缶詰',
    items: [
      ['harusame', '春雨'],
      ['tuna_can', 'ツナ缶'],
      ['tomato_can', 'トマト缶'],
      ['katakuriko', '片栗粉'],
      ['rice', '米'],
      ['pasta', 'パスタ'],
      ['udon', 'うどん'],
      ['chuka_men', '中華麺'],
      ['panko', 'パン粉'],
      ['flour', '小麦粉'],
      ['hijiki', 'ひじき'],
      ['kiriboshi_daikon', '切り干し大根'],
    ],
  },
  {
    key: 'dairy',
    label: '乳製品',
    items: [
      ['cheese', 'チーズ'],
      ['milk', '牛乳'],
      ['butter', 'バター'],
      ['cream', '生クリーム'],
      ['yogurt', 'ヨーグルト'],
    ],
  },
];

// 調味料タブ定義
const SEASONING_TABS = [
  {
    key: 'japanese',
    label: '和',
    items: [
      ['soy_sauce', '醤油'],
      ['miso', '味噌'],
      ['mirin', 'みりん'],
      ['sake', '酒'],
      ['sugar', '砂糖'],
      ['dashi', 'だし'],
      ['vinegar', '酢'],
      ['mentsuyu', 'めんつゆ'],
    ],
  },
  {
    key: 'western',
    label: '洋',
    items: [
      ['salt', '塩'],
      ['pepper', 'こしょう'],
      ['olive_oil', 'オリーブオイル'],
      ['consomme', 'コンソメ'],
      ['ketchup', 'ケチャップ'],
      ['mayo', 'マヨネーズ'],
      ['worcester', 'ウスターソース'],
    ],
  },
  {
    key: 'chinese',
    label: '中',
    items: [
      ['oyster_sauce', 'オイスターソース'],
      ['doubanjiang', '豆板醤'],
      ['sesame_oil', 'ごま油'],
      ['chuka_dashi', '中華だし'],
      ['tenmenjan', '甜麺醤'],
    ],
  },
  {
    key: 'other',
    label: 'その他',
    items: [
      ['curry_roux', 'カレールー'],
      ['oil', '油'],
      ['ponzu', 'ポン酢'],
      ['dashi_soy', 'だし醤油'],
    ],
  },
];

// 1人前あたりの目安量（食材ID -> 分量）。fixed のものは人数によらず一定量を表示する
const INGREDIENT_SERVING_INFO = {
  pork: { amount: 100, unit: 'g' },
  chicken: { amount: 100, unit: 'g' },
  beef: { amount: 100, unit: 'g' },
  chicken_mince: { amount: 80, unit: 'g' },
  pork_mince: { amount: 80, unit: 'g' },
  mixed_mince: { amount: 80, unit: 'g' },
  bacon: { amount: 1, unit: '枚' },
  sausage: { amount: 1.5, unit: '本' },
  egg: { amount: 1, unit: '個' },
  tofu: { amount: 0.5, unit: '丁' },
  atsuage: { amount: 0.5, unit: '枚' },
  natto: { amount: 1, unit: 'パック' },
  onion: { amount: 0.5, unit: '個' },
  carrot: { amount: 0.5, unit: '本' },
  cabbage: { amount: 100, unit: 'g' },
  potato: { amount: 1, unit: '個' },
  nasu: { amount: 1, unit: '本' },
  tomato: { amount: 0.5, unit: '個' },
  minitomato: { amount: 4, unit: '個' },
  cucumber: { amount: 0.5, unit: '本' },
  piman: { amount: 1, unit: '個' },
  moyashi: { amount: 0.5, unit: '袋' },
  negi: { amount: 0.5, unit: '本' },
  garlic: { amount: 1, unit: '片' },
  ginger: { amount: 1, unit: '片' },
  mushroom: { amount: 50, unit: 'g' },
  daikon: { amount: 100, unit: 'g' },
  lettuce: { amount: 2, unit: '枚' },
  spinach_frozen: { amount: 50, unit: 'g' },
  broccoli_frozen: { amount: 50, unit: 'g' },
  corn_frozen: { amount: 30, unit: 'g' },
  harusame: { amount: 20, unit: 'g' },
  tuna_can: { amount: 0.5, unit: '缶' },
  tomato_can: { amount: 0.5, unit: '缶' },
  katakuriko: { amount: 1, unit: '小さじ' },
  rice: { amount: 0.5, unit: '合' },
  pasta: { amount: 100, unit: 'g' },
  udon: { amount: 1, unit: '玉' },
  chuka_men: { amount: 1, unit: '玉' },
  panko: { amount: 2, unit: '大さじ' },
  flour: { amount: 2, unit: '大さじ' },
  hijiki: { amount: 5, unit: 'g' },
  kiriboshi_daikon: { amount: 15, unit: 'g' },
  cheese: { amount: 20, unit: 'g' },
  milk: { amount: 50, unit: 'ml' },
  butter: { amount: 10, unit: 'g' },
  cream: { amount: 50, unit: 'ml' },
  yogurt: { amount: 50, unit: 'g' },
  soy_sauce: { amount: 0.5, unit: '大さじ' },
  miso: { amount: 0.5, unit: '大さじ' },
  mirin: { amount: 0.5, unit: '大さじ' },
  sake: { amount: 0.5, unit: '大さじ' },
  sugar: { amount: 1, unit: '小さじ' },
  dashi: { amount: 100, unit: 'ml' },
  vinegar: { amount: 1, unit: '小さじ' },
  mentsuyu: { amount: 0.5, unit: '大さじ' },
  salt: { fixed: '少々' },
  pepper: { fixed: '少々' },
  olive_oil: { amount: 0.5, unit: '大さじ' },
  consomme: { amount: 1, unit: '小さじ' },
  ketchup: { amount: 1, unit: '大さじ' },
  mayo: { amount: 1, unit: '大さじ' },
  worcester: { amount: 1, unit: '小さじ' },
  oyster_sauce: { amount: 1, unit: '小さじ' },
  doubanjiang: { amount: 0.5, unit: '小さじ' },
  sesame_oil: { amount: 1, unit: '小さじ' },
  chuka_dashi: { amount: 0.5, unit: '小さじ' },
  tenmenjan: { amount: 1, unit: '小さじ' },
  curry_roux: { amount: 1, unit: 'かけ' },
  oil: { amount: 1, unit: '大さじ' },
  ponzu: { amount: 1, unit: '大さじ' },
  dashi_soy: { amount: 0.5, unit: '大さじ' },
};

// 料理データベース（100品: 和30 / 中30 / 洋30 / 他10）
const DISHES = [
  // ===== 和食 30品 =====
  { name: '肉じゃが', genre: '和', time: 30, description: 'じゃがいもにだしがしみ込む、日本の家庭料理の代表格。', need: ['pork', 'onion', 'potato', 'carrot', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['豚肉と野菜を一口大に切る。', '鍋で豚肉を炒め、色が変わったら玉ねぎ・にんじん・じゃがいもを加えてさらに炒める。', 'だし汁を加えて煮立たせ、アクを取りながら弱火で10分煮る。', '醤油・みりん・砂糖を加え、じゃがいもが柔らかくなるまで煮含める。'], tips: ['じゃがいもは煮崩れしにくいメークインがおすすめ。', '落し蓋をして弱火でじっくり煮ると、味が均一にしみ込む。'] },
  { name: '豚の生姜焼き', genre: '和', time: 20, description: 'しょうがの香りと甘辛いタレが食欲をそそる定番おかず。', need: ['pork', 'onion', 'ginger', 'soy_sauce', 'mirin', 'sugar'], steps: ['豚肉に軽く塩こしょうし、玉ねぎを薄切りにする。', 'しょうが・醤油・みりん・砂糖を混ぜてタレを作る。', 'フライパンで玉ねぎと豚肉を炒め、火が通ったらタレを絡めて仕上げる。'], tips: ['肉は焼く直前にタレに漬けると硬くなりにくい。', '強火でさっと焼き、タレは仕上げに絡めると香りが飛びにくい。'] },
  { name: '鶏の照り焼き', genre: '和', time: 20, description: '皮はパリッと、身はジューシーに仕上げる甘辛だれの一品。', need: ['chicken', 'soy_sauce', 'mirin', 'sugar', 'sake'], steps: ['鶏肉に切り込みを入れ、皮目から焼く。', '両面に焼き色がついたら余分な油を拭き取る。', '醤油・みりん・砂糖・酒を加え、とろみがつくまで煮絡める。'], tips: ['皮目を押さえながら焼くと縮まず均一に焼ける。', '余分な脂を拭き取ってからタレを絡めると照りよく仕上がる。'] },
  { name: '肉豆腐', genre: '和', time: 20, description: '牛肉の旨みを豆腐が吸い込む、すき焼き風の煮物。', need: ['beef', 'tofu', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['豆腐は一口大、長ねぎは斜め切りにする。', '鍋にだし・醤油・みりん・砂糖を煮立て、牛肉を加えて煮る。', '豆腐と長ねぎを加え、味がなじむまで煮る。'], tips: ['豆腐は先に軽く焼き付けると崩れにくく味もしみやすい。', '煮すぎず、味を含ませたら早めに火を止める。'] },
  { name: '豚汁', genre: '和', time: 30, description: '具だくさんで体が温まる、みそ仕立ての汁物。', need: ['pork', 'daikon', 'carrot', 'negi', 'miso', 'dashi'], steps: ['豚肉と大根・にんじんを一口大に切る。', '鍋で豚肉を炒め、大根・にんじん・長ねぎを加えて炒める。', 'だしを加えて煮込み、野菜が柔らかくなったら味噌を溶き入れる。'], tips: ['味噌は煮立てず、火を止める直前に溶き入れると香りが立つ。', '根菜は先に炒めてから煮ると旨みが増す。'] },
  { name: '筑前煮', genre: '和', time: 45, description: '鶏肉と根菜を炒めてから煮る、コクのある煮物。', need: ['chicken', 'carrot', 'daikon', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['鶏肉・にんじん・大根・きのこを一口大に切る。', '鍋で鶏肉を炒め、野菜を加えてさらに炒める。', 'だしを加えて煮立て、醤油・みりん・砂糖を加えて弱火でコトコト煮含める。'], tips: ['油で炒めてから煮ると具材の旨みが閉じ込められる。', '面取りをすると煮崩れを防げる。'] },
  { name: '肉巻き野菜', genre: '和', time: 20, description: '野菜を豚肉で巻いて食べ応えとバランスを両立させた一品。', need: ['pork', 'carrot', 'piman', 'soy_sauce', 'mirin', 'sugar'], steps: ['にんじん・ピーマンを細切りにし、豚肉で巻く。', '巻き終わりを下にしてフライパンで焼き、全面に焼き色をつける。', '醤油・みりん・砂糖を加えて煮絡める。'], tips: ['巻き終わりを下にして焼き始めると型崩れしない。', '巻く前に野菜へ軽く片栗粉をまぶすと肉が密着する。'] },
  { name: '親子丼', genre: '和', time: 20, description: '卵のとろみと出汁の風味が親しみやすい定番丼。', need: ['chicken', 'egg', 'onion', 'soy_sauce', 'mirin', 'sugar', 'dashi', 'rice'], steps: ['鶏肉と玉ねぎを一口大に切る。', 'だし・醤油・みりん・砂糖を煮立て、鶏肉と玉ねぎを煮る。', '溶き卵を回し入れ、半熟になったらご飯にのせる。'], tips: ['卵は2回に分けて入れ、半熟のところで火を止めると綺麗に仕上がる。', '鍋を揺すりながら煮ると卵がふんわり仕上がる。'] },
  { name: 'だし巻き卵', genre: '和', time: 10, description: 'だしをたっぷり含ませてふんわり焼き上げる卵料理。', need: ['egg', 'soy_sauce', 'sugar', 'dashi'], steps: ['卵にだし・醤油・砂糖を混ぜる。', '卵焼き器を温め、卵液を数回に分けて流し入れながら巻く。', '形を整えて焼き上げ、食べやすい大きさに切る。'], tips: ['卵液は濾すとなめらかな食感になる。', '巻くたびに油を薄くひくと焦げ付きにくい。'] },
  { name: '豆腐ハンバーグ', genre: '和', time: 30, description: '豆腐でふんわり軽く仕上げたヘルシーなハンバーグ。', need: ['tofu', 'mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce'], steps: ['豆腐は水切りし、玉ねぎはみじん切りにして炒める。', '合いびき肉・豆腐・卵・パン粉・炒めた玉ねぎを混ぜて成形する。', 'フライパンで両面を焼き、中まで火を通す。', '醤油ベースのタレをかけて仕上げる。'], tips: ['豆腐はしっかり水切りするとタネがまとまりやすい。', '蓋をして蒸し焼きにすると中まで均一に火が通る。'] },
  { name: 'すき焼き風煮', genre: '和', time: 30, description: '甘辛い割り下で牛肉と豆腐を煮込むすき焼き風の一皿。', need: ['beef', 'tofu', 'negi', 'mushroom', 'soy_sauce', 'mirin', 'sugar', 'sake'], steps: ['長ねぎ・きのこを食べやすく切る。', '鍋に醤油・みりん・砂糖・酒を煮立て、牛肉をさっと煮る。', '豆腐・長ねぎ・きのこを加えて煮含める。'], tips: ['牛肉は煮すぎず、さっと火を通す程度で取り出すと柔らかい。', '野菜から出る水分を考えて調味料を控えめにする。'] },
  { name: '豚しゃぶサラダ', genre: '和', time: 20, description: 'さっぱりポン酢で食べる、茹で豚と野菜のサラダ。', need: ['pork', 'lettuce', 'cucumber', 'ponzu'], steps: ['豚肉を熱湯でさっと茹でて冷ます。', 'レタス・きゅうりを食べやすく切って皿に盛る。', '豚肉をのせてポン酢をかける。'], tips: ['茹でた豚肉は氷水で締めると余熱で硬くならない。', '茹で汁に酒を少し加えると肉の臭みが抜ける。'] },
  { name: '鶏そぼろ丼', genre: '和', time: 20, description: 'そぼろと炒り卵の彩りが美しい二色丼。', need: ['chicken_mince', 'egg', 'soy_sauce', 'mirin', 'sugar', 'rice'], steps: ['鍋に鶏ひき肉・醤油・みりん・砂糖を入れ、ほぐしながら炒り煮する。', '別鍋で炒り卵を作る。', 'ご飯にそぼろと炒り卵を盛りつける。'], tips: ['そぼろは菜箸4〜5本でほぐしながら煮るとパラパラに仕上がる。', '煮汁が少し残る程度で火を止めるとしっとり仕上がる。'] },
  { name: '厚揚げの煮物', genre: '和', time: 20, description: '厚揚げが出汁を吸ってジューシーになる煮物。', need: ['atsuage', 'daikon', 'negi', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['厚揚げは食べやすく切り、大根は薄いいちょう切りにする。', '鍋にだし・醤油・みりん・砂糖を煮立て、大根と厚揚げを加える。', '弱火で煮含め、長ねぎを加えてひと煮立ちさせる。'], tips: ['厚揚げは熱湯をかけて油抜きすると味がしみやすい。', '大根は下茹でしておくと味の入りが早い。'] },
  { name: '豚バラ大根', genre: '和', time: 45, description: '豚バラの脂と大根の甘みが染み合う煮込み料理。', need: ['pork', 'daikon', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['大根は厚めの半月切りにし、下茹でしておく。', '豚バラ肉を炒め、大根を加えてさらに炒める。', 'だし・醤油・みりん・砂糖を加え、大根が柔らかくなるまで煮込む。'], tips: ['大根は下茹ですると臭みが取れ、味がしみやすくなる。', '豚バラは先に炒めて余分な脂を出しておくとくどくならない。'] },
  { name: '鶏の唐揚げ', genre: '和', time: 20, description: '外はカリッと中はジューシーな定番の揚げ物。', need: ['chicken', 'soy_sauce', 'sake', 'ginger', 'garlic', 'katakuriko', 'oil'], steps: ['鶏肉を一口大に切り、醤油・酒・しょうが・にんにくに漬け込む。', '汁気を軽く切り、片栗粉をまぶす。', '170℃の油できつね色になるまで揚げる。'], tips: ['二度揚げすると外側がよりカリッと仕上がる。', '揚げる直前に片栗粉をまぶすと衣がべたつかない。'] },
  { name: 'じゃがいもの煮っころがし', genre: '和', time: 20, description: 'じゃがいもを転がしながら照りよく煮詰めた素朴な一品。', need: ['potato', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['じゃがいもを一口大に切る。', '鍋で軽く炒め、だし・醤油・みりん・砂糖を加える。', '落し蓋をして煮汁が少なくなるまで転がしながら煮る。'], tips: ['煮汁が少なくなったら鍋を揺すって全体に絡める。', 'じゃがいもの角を軽く面取りすると煮崩れしにくい。'] },
  { name: 'なすの煮浸し', genre: '和', time: 20, description: 'なすが出汁をたっぷり吸った、冷やしても美味しい一品。', need: ['nasu', 'dashi', 'soy_sauce', 'mirin'], steps: ['なすを乱切りにし、油でさっと炒める。', 'だし・醤油・みりんを煮立て、なすを加える。', '味を含ませながら煮て、冷ましても美味しい。'], tips: ['なすは油通しすると色よく仕上がり口当たりも良くなる。', '熱いうちに出汁に浸すと味の入りが早い。'] },
  { name: 'ひじきの煮物', genre: '和', time: 30, description: 'ひじきと根菜を甘辛く煮た常備菜の定番。', need: ['hijiki', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['ひじきを水で戻し、にんじんは細切りにする。', '鍋で油ひじき・にんじん・厚揚げを炒める。', 'だし・醤油・みりん・砂糖を加え、汁気がなくなるまで煮る。'], tips: ['ひじきは戻しすぎると風味が抜けるので表示時間を守る。', '油で炒めてから煮ると香りとコクが増す。'] },
  { name: '切り干し大根の煮物', genre: '和', time: 30, description: '切り干し大根の甘みと旨みが凝縮した常備菜。', need: ['kiriboshi_daikon', 'carrot', 'atsuage', 'soy_sauce', 'mirin', 'sugar', 'dashi'], steps: ['切り干し大根を水で戻し、水気を絞る。', 'にんじん・厚揚げと一緒に油で炒める。', 'だし・醤油・みりん・砂糖を加えて煮含める。'], tips: ['戻し汁は旨みが出ているので煮汁に使うと風味が増す。', '水気をしっかり絞ってから炒めると味がぼやけない。'] },
  { name: '豚しゃぶ鍋', genre: '和', time: 30, description: '野菜と豚肉を出汁でしゃぶしゃぶする体に優しい鍋。', need: ['pork', 'cabbage', 'negi', 'mushroom', 'tofu', 'dashi', 'soy_sauce'], steps: ['キャベツ・長ねぎ・きのこ・豆腐を食べやすく切る。', '鍋にだしと醤油を入れて煮立てる。', '野菜を煮ながら豚肉をしゃぶしゃぶして食べる。'], tips: ['肉は色が変わる程度でさっと引き上げると柔らかい。', 'アクをこまめに取ると出汁が澄んで美味しくなる。'] },
  { name: '焼き鳥丼', genre: '和', time: 20, description: '香ばしく焼いた鶏と甘辛だれが絡む丼。', need: ['chicken', 'negi', 'soy_sauce', 'mirin', 'sugar', 'sake', 'rice'], steps: ['鶏肉と長ねぎを一口大に切る。', 'フライパンで焼き色をつけながら焼く。', '醤油・みりん・砂糖・酒のタレを絡め、ご飯にのせる。'], tips: ['皮目からしっかり焼いて余分な脂を落とすと香ばしくなる。', 'タレは煮詰めてとろみをつけると絡みが良くなる。'] },
  { name: '和風ハンバーグ', genre: '和', time: 30, description: '大根おろしと和風だれでさっぱり食べるハンバーグ。', need: ['mixed_mince', 'egg', 'panko', 'onion', 'soy_sauce', 'mirin', 'sugar', 'daikon'], steps: ['玉ねぎをみじん切りにして炒め、冷ましておく。', '合いびき肉・卵・パン粉・玉ねぎを混ぜて成形し、焼く。', '大根おろしと醤油・みりん・砂糖のタレをかける。'], tips: ['タネはよく練って粘りを出すと肉汁が閉じ込められる。', '焼いたあと少し休ませると肉汁が落ち着き切りやすい。'] },
  { name: '卵とじうどん', genre: '和', time: 20, description: 'だしの効いたつゆに卵をふんわりとじたうどん。', need: ['udon', 'egg', 'negi', 'dashi', 'soy_sauce', 'mirin'], steps: ['うどんを表示通りに茹でる。', 'だし・醤油・みりんを煮立て、長ねぎを加える。', 'うどんを加えて温め、溶き卵を回し入れてとじる。'], tips: ['煮立てすぎると卵が固くなるので火を弱めてから加える。', '溶き卵は菜箸を伝わせて細く流し入れるとふんわりする。'] },
  { name: '肉うどん', genre: '和', time: 20, description: '牛肉の旨みが染みた甘辛いつゆのうどん。', need: ['udon', 'beef', 'negi', 'dashi', 'soy_sauce', 'mirin', 'sugar'], steps: ['うどんを表示通りに茹でる。', 'だし・醤油・みりん・砂糖を煮立て、牛肉と長ねぎを煮る。', '器にうどんを盛り、煮た具と汁をかける。'], tips: ['牛肉は煮すぎず、色が変わったらすぐに取り出す。', 'つゆは一度煮立ててアクを取ると雑味が減る。'] },
  { name: '豚の味噌漬け焼き', genre: '和', time: 20, description: '味噌に漬け込むことで旨みと風味が増す焼き物。', need: ['pork', 'miso', 'mirin', 'sugar', 'sake'], steps: ['味噌・みりん・砂糖・酒を混ぜて豚肉に漬け込む。', '味噌を軽く拭き取り、焦げないよう弱めの火で焼く。', '中まで火が通ったら切り分ける。'], tips: ['味噌は焦げやすいので中火以下でじっくり焼く。', '漬け込み時間を長くするほど味が深まる。'] },
  { name: '厚揚げの照り焼き', genre: '和', time: 20, description: '厚揚げを香ばしく焼いて甘辛だれを絡めた一品。', need: ['atsuage', 'negi', 'soy_sauce', 'mirin', 'sugar', 'katakuriko'], steps: ['厚揚げを一口大に切り、片栗粉を薄くまぶす。', 'フライパンで焼き色がつくまで焼く。', '醤油・みりん・砂糖のタレを絡め、長ねぎを散らす。'], tips: ['片栗粉をまぶして焼くとタレがよく絡む。', '強火で表面をカリッと焼くと食感が良くなる。'] },
  { name: '鶏むね肉のマヨポン炒め', genre: '和', time: 20, description: 'パサつきがちな鶏むね肉をマヨでしっとり仕上げる炒め物。', need: ['chicken', 'mayo', 'ponzu', 'negi'], steps: ['鶏むね肉を一口大に切る。', 'フライパンで焼き、火が通ったら長ねぎを加える。', 'マヨネーズとポン酢を加えて絡める。'], tips: ['鶏むね肉は薄いそぎ切りにすると火が通りやすく柔らかい。', 'マヨネーズを先に絡めて焼くとコクが出てパサつきにくい。'] },
  { name: '豚肉と白菜風煮浸し', genre: '和', time: 20, description: 'キャベツと豚肉を出汁でやさしく煮た一品。', need: ['pork', 'cabbage', 'dashi', 'soy_sauce', 'mirin'], steps: ['キャベツはざく切り、豚肉は食べやすく切る。', '鍋でさっと炒め、だし・醤油・みりんを加える。', '蓋をして柔らかくなるまで煮浸しにする。'], tips: ['蓋をして蒸し煮にすると野菜の甘みが引き出される。', '豚肉は最後に加えてさっと火を通すと硬くならない。'] },
  { name: '冷奴', genre: '和', time: 10, description: '薬味と醤油だけで豆腐の美味しさを味わうシンプルな一品。', need: ['tofu', 'negi', 'soy_sauce'], steps: ['豆腐を食べやすく切って器に盛る。', '長ねぎを小口切りにしてのせる。', '醤油をかけて完成。'], tips: ['豆腐は食べる直前まで冷やしておくと美味しさが引き立つ。', '水切りを軽くしておくと薬味の味がぼやけない。'] },

  // ===== 中華 30品 =====
  { name: '麻婆豆腐', genre: '中', time: 20, description: '豆板醤の辛みと痺れが効いた本格中華の定番。', need: ['tofu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'ginger', 'katakuriko', 'chuka_dashi'], steps: ['豆腐は角切りにし、湯通ししておく。', '豚ひき肉・にんにく・しょうがを炒め、豆板醤を加えて香りを出す。', '中華だし・醤油・砂糖を加えて煮立て、豆腐を加える。', '水溶き片栗粉でとろみをつける。'], tips: ['豆腐は下茹ですると崩れにくく、味もしみ込みやすい。', '仕上げにごま油を回しかけると香りが立つ。'] },
  { name: '青椒肉絲', genre: '中', time: 20, description: '牛肉とピーマンの食感を活かしたシャキシャキ炒め。', need: ['beef', 'piman', 'oyster_sauce', 'soy_sauce', 'sugar', 'katakuriko', 'garlic'], steps: ['牛肉とピーマンを細切りにする。', '牛肉に片栗粉をまぶして炒める。', 'ピーマン・にんにくを加えて炒め、オイスターソース・醤油・砂糖で味付けする。'], tips: ['肉は繊維に沿って細切りにすると炒めても縮みにくい。', '強火・短時間でさっと炒めると野菜の食感が残る。'] },
  { name: '回鍋肉', genre: '中', time: 20, description: '豆板醤と味噌でコクを出した本場風キャベツ炒め。', need: ['pork', 'cabbage', 'doubanjiang', 'miso', 'sugar', 'garlic'], steps: ['豚肉とキャベツを一口大に切る。', 'にんにくを炒めて香りを出し、豚肉を炒める。', 'キャベツを加えて炒め、豆板醤・味噌・砂糖で味付けする。'], tips: ['豚肉は一度茹でてから炒めると余分な脂が落ちて香ばしい。', 'キャベツは大きめにちぎると食感が楽しめる。'] },
  { name: '酢豚', genre: '中', time: 30, description: '甘酢だれと揚げた豚肉が絡み合う定番中華。', need: ['pork', 'piman', 'onion', 'carrot', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'katakuriko'], steps: ['豚肉に片栗粉をまぶして揚げ焼きにする。', '玉ねぎ・にんじん・ピーマンを炒める。', 'ケチャップ・酢・砂糖・醤油を混ぜたタレを加え、豚肉を戻して絡める。'], tips: ['豚肉は二度揚げすると衣がカリッと長持ちする。', '野菜は炒めすぎず食感を残すと美味しい。'] },
  { name: '餃子', genre: '中', time: 45, description: 'パリッと焼いた皮と肉汁たっぷりの餡が魅力の一品。', need: ['pork_mince', 'cabbage', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'katakuriko'], steps: ['キャベツをみじん切りにして塩もみし、水気を絞る。', '豚ひき肉・キャベツ・にんにく・しょうが・醤油・ごま油を混ぜて餡を作る。', '皮に包み、フライパンで焼いて蒸し焼きにする。'], tips: ['焼くときは水を加えて蒸し焼きにし、最後に油を足すとパリッと仕上がる。', '餡はよく練ると肉汁が閉じ込められる。'] },
  { name: '春巻き', genre: '中', time: 30, description: 'サクサクの皮の中に旨みたっぷりの具が詰まった揚げ物。', need: ['pork_mince', 'harusame', 'carrot', 'cabbage', 'oyster_sauce', 'sesame_oil'], steps: ['春雨は戻して切り、にんじん・キャベツは細切りにする。', '豚ひき肉と野菜をオイスターソース・ごま油で炒めて具を作る。', '皮で包み、油で揚げる。'], tips: ['具材の水分をしっかり飛ばしてから包むと皮がベタつかない。', '巻き終わりは水溶き小麦粉でしっかり留める。'] },
  { name: '中華丼', genre: '中', time: 20, description: 'とろみのある餡と具だくさんの野菜がご飯に絡む一品。', need: ['pork', 'cabbage', 'carrot', 'mushroom', 'oyster_sauce', 'chuka_dashi', 'katakuriko', 'rice'], steps: ['豚肉・キャベツ・にんじん・きのこを一口大に切る。', '炒めて中華だし・オイスターソースで味付けする。', '水溶き片栗粉でとろみをつけ、ご飯にかける。'], tips: ['水溶き片栗粉は一気に加え手早く混ぜるとダマになりにくい。', '野菜は火の通りにくい順に加えると仕上がりが均一になる。'] },
  { name: '麻婆春雨', genre: '中', time: 20, description: '春雨がスープを吸い込んで旨みたっぷりに仕上がる一品。', need: ['pork_mince', 'harusame', 'doubanjiang', 'soy_sauce', 'garlic', 'chuka_dashi'], steps: ['春雨は熱湯で戻しておく。', '豚ひき肉・にんにくを炒め、豆板醤を加える。', '中華だし・醤油と春雨を加えて汁気を吸わせるように煮る。'], tips: ['春雨は煮すぎると伸びるので仕上げ直前に加える。', '豆板醤は焦がさないよう弱火でじっくり炒めて香りを出す。'] },
  { name: '天津飯', genre: '中', time: 20, description: 'ふわとろ卵にとろみあんをかけた中華丼もの。', need: ['egg', 'tuna_can', 'katakuriko', 'chuka_dashi', 'soy_sauce', 'rice'], steps: ['卵にツナを混ぜて溶いておく。', 'フライパンで半熟に焼き、ご飯にのせる。', '中華だし・醤油・水溶き片栗粉であんを作りかける。'], tips: ['卵は半熟で取り出し、余熱で火を通すとふんわり仕上がる。', 'あんは仕上げにごま油を垂らすと風味が増す。'] },
  { name: '棒々鶏', genre: '中', time: 20, description: '茹で鶏に香ばしいごまだれをかけた冷菜。', need: ['chicken', 'cucumber', 'sesame_oil', 'soy_sauce', 'sugar', 'vinegar'], steps: ['鶏肉を茹でて冷まし、手で細かく裂く。', 'きゅうりを細切りにして皿に盛る。', '醤油・砂糖・酢・ごま油を混ぜたタレをかける。'], tips: ['鶏肉は茹で汁の中で冷ますとしっとり仕上がる。', '手で裂くと繊維に沿ってほぐれ食感が良くなる。'] },
  { name: 'よだれ鶏', genre: '中', time: 20, description: '花椒や酢が効いた四川風の痺れ辛だれが決め手の冷菜。', need: ['chicken', 'negi', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil', 'vinegar'], steps: ['鶏肉を茹でて冷まし、食べやすく切る。', 'にんにく・しょうがをみじん切りにする。', '醤油・酢・ごま油・にんにく・しょうがを混ぜたタレをかける。'], tips: ['鶏肉は茹で上げ後すぐ氷水に取ると身が締まる。', 'タレは食べる直前にかけると香りが飛ばない。'] },
  { name: '鶏の甘酢あん', genre: '中', time: 20, description: '揚げた鶏肉に甘酸っぱいあんを絡めた一品。', need: ['chicken', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce'], steps: ['鶏肉に片栗粉をまぶして揚げ焼きにする。', 'ケチャップ・酢・砂糖・醤油を煮立ててタレを作る。', '鶏肉にタレを絡める。'], tips: ['揚げたてにあんを絡めると衣がべたつきにくい。', 'あんは煮詰めすぎず、とろみが出たらすぐ火を止める。'] },
  { name: '豚肉と厚揚げの中華炒め', genre: '中', time: 20, description: '厚揚げのコクと豚肉の旨みが合わさった炒め物。', need: ['pork', 'atsuage', 'negi', 'oyster_sauce', 'garlic'], steps: ['豚肉と厚揚げを一口大に切る。', 'にんにくを炒めて香りを出し、豚肉を炒める。', '厚揚げと長ねぎを加え、オイスターソースで味付けする。'], tips: ['厚揚げは油抜きしてから炒めると味がしみやすい。', 'にんにくは焦がさないよう弱火で香りを出す。'] },
  { name: 'もやし玉子炒め', genre: '中', time: 10, description: 'もやしのシャキシャキ感を活かした手早い卵炒め。', need: ['egg', 'moyashi', 'negi', 'sesame_oil', 'salt', 'pepper'], steps: ['もやしをさっと洗い、長ねぎを小口切りにする。', '卵を溶いてごま油で炒め、半熟で取り出す。', 'もやしと長ねぎを炒め、卵を戻して塩こしょうで味を調える。'], tips: ['もやしは水気をよく切ってから炒めると水っぽくならない。', '卵は半熟で一度取り出し、最後に戻すとふんわり仕上がる。'] },
  { name: '豚肉と白菜の中華煮込み', genre: '中', time: 20, description: '野菜の甘みが溶け込んだとろみのある煮込み。', need: ['pork', 'cabbage', 'mushroom', 'chuka_dashi', 'oyster_sauce', 'katakuriko'], steps: ['豚肉とキャベツ・きのこを食べやすく切る。', '炒めてから中華だしを加えて煮る。', 'オイスターソースと水溶き片栗粉でとろみをつける。'], tips: ['キャベツは芯から炒めると火の通りが均一になる。', 'とろみは仕上げ直前につけると水っぽくならない。'] },
  { name: '麻婆なす', genre: '中', time: 20, description: '揚げ焼きしたなすが豆板醤の辛みを吸った一品。', need: ['nasu', 'pork_mince', 'doubanjiang', 'soy_sauce', 'sugar', 'garlic', 'katakuriko'], steps: ['なすを乱切りにして炒める。', '豚ひき肉・にんにくを炒め、豆板醤を加える。', 'なすを戻し、醤油・砂糖と水溶き片栗粉でとろみをつける。'], tips: ['なすは油で揚げ焼きにすると色よく煮崩れしにくい。', 'なすを先に取り出し、あんと絡めるのは最後にする。'] },
  { name: '担々麺', genre: '中', time: 20, description: 'ごまと辛みの効いた肉味噌が絡む中華麺。', need: ['chuka_men', 'pork_mince', 'doubanjiang', 'sesame_oil', 'chuka_dashi', 'miso'], steps: ['中華麺を表示通りに茹でる。', '豚ひき肉・豆板醤を炒め、味噌・中華だしで肉味噌を作る。', 'ごま油を加えたスープに麺を入れ、肉味噌をのせる。'], tips: ['肉味噌は豆板醤を弱火でじっくり炒めて香りを引き出す。', 'スープと具は別に用意し、食べる直前に合わせる。'] },
  { name: 'ジャージャー麺', genre: '中', time: 20, description: '甜麺醤ベースの濃厚な肉味噌をのせた中華麺。', need: ['chuka_men', 'pork_mince', 'tenmenjan', 'miso', 'garlic', 'katakuriko'], steps: ['中華麺を茹でておく。', '豚ひき肉・にんにくを炒め、甜麺醤・味噌で肉味噌を作る。', '水溶き片栗粉でとろみをつけ、麺にのせる。'], tips: ['肉味噌は少量の水を加えて煮詰めると味がなじむ。', '麺は熱いうちに肉味噌と和えると絡みが良くなる。'] },
  { name: '八宝菜', genre: '中', time: 45, description: '彩り豊かな具材を一皿にまとめたとろみ炒め。', need: ['pork', 'cabbage', 'carrot', 'mushroom', 'moyashi', 'chuka_dashi', 'katakuriko', 'oyster_sauce'], steps: ['豚肉・キャベツ・にんじん・きのこ・もやしを食べやすく切る。', '豚肉から炒め、野菜を加えてさらに炒める。', '中華だし・オイスターソースを加え、水溶き片栗粉でとろみをつける。'], tips: ['具材は火の通りにくいものから順に炒める。', 'とろみは水溶き片栗粉を少しずつ加えて調整する。'] },
  { name: '肉団子の甘酢あん', genre: '中', time: 30, description: '揚げた肉団子に甘酢あんを絡めたご飯が進む一品。', need: ['mixed_mince', 'katakuriko', 'ketchup', 'vinegar', 'sugar', 'soy_sauce', 'egg'], steps: ['合いびき肉に片栗粉・卵を混ぜて団子状に丸め、揚げ焼きにする。', 'ケチャップ・酢・砂糖・醤油でタレを作る。', '団子にタレを絡める。'], tips: ['肉だねは手で叩きつけて空気を抜くと崩れにくい。', '低めの油温でじっくり揚げると中まで火が通る。'] },
  { name: '中華風炒り豆腐', genre: '中', time: 20, description: '豆腐と卵をふんわり炒め合わせた優しい味わいの一品。', need: ['tofu', 'egg', 'negi', 'oyster_sauce', 'sesame_oil'], steps: ['豆腐を崩して水気を切る。', 'ごま油で豆腐と長ねぎを炒める。', '溶き卵を加え、オイスターソースで味付けする。'], tips: ['豆腐は水切りしてから炒めると水っぽくならない。', '卵は半熟のタイミングで火を止めるとふんわり仕上がる。'] },
  { name: 'ブロッコリー炒め', genre: '中', time: 10, description: 'にんにくの香りを効かせたシンプルな野菜炒め。', need: ['broccoli_frozen', 'garlic', 'oyster_sauce', 'sesame_oil'], steps: ['ブロッコリーは解凍しておく。', 'にんにくをごま油で炒めて香りを出す。', 'ブロッコリーを加えて炒め、オイスターソースで味付けする。'], tips: ['ブロッコリーは霜取りする程度で炒めると食感が残る。', 'にんにくは弱火でゆっくり香りを引き出す。'] },
  { name: 'もやしと豚肉の中華炒め', genre: '中', time: 20, description: '手早く仕上がる、シャキシャキのもやしと豚肉の炒め物。', need: ['pork', 'moyashi', 'negi', 'oyster_sauce', 'sesame_oil', 'garlic'], steps: ['豚肉ともやし・長ねぎを用意する。', 'にんにくを炒めて豚肉を加える。', 'もやし・長ねぎを加えて炒め、オイスターソース・ごま油で味付けする。'], tips: ['もやしは最後に加えて短時間で炒めると食感が残る。', '強火で一気に炒めると水っぽくならない。'] },
  { name: 'あんかけ焼きそば', genre: '中', time: 30, description: 'カリッと焼いた麺ととろみ餡の対比が楽しい一品。', need: ['chuka_men', 'pork', 'cabbage', 'carrot', 'mushroom', 'chuka_dashi', 'katakuriko', 'oyster_sauce'], steps: ['中華麺を焼いてカリッとさせる。', '豚肉・キャベツ・にんじん・きのこを炒める。', '中華だし・オイスターソースを加え、水溶き片栗粉でとろみをつけて麺にかける。'], tips: ['麺は動かさずじっくり焼き付けるとカリッと仕上がる。', 'あんは麺にかける直前に仕上げると食感が保たれる。'] },
  { name: '鶏肉と厚揚げの中華煮', genre: '中', time: 30, description: '鶏肉と厚揚げが出汁を吸い合う優しい煮込み。', need: ['chicken', 'atsuage', 'negi', 'chuka_dashi', 'oyster_sauce', 'katakuriko'], steps: ['鶏肉と厚揚げを一口大に切る。', '炒めてから中華だしを加えて煮る。', 'オイスターソースと水溶き片栗粉でとろみをつける。'], tips: ['厚揚げは油抜きしてから加えると味がしみやすい。', '鶏肉は皮目から焼き付けると香ばしさが増す。'] },
  { name: '豚バラともやしのレンジ蒸し', genre: '中', time: 20, description: 'レンジで手軽に作れる、あっさり蒸し料理。', need: ['pork', 'moyashi', 'negi', 'sesame_oil', 'salt'], steps: ['もやしを耐熱皿に敷き、豚肉をのせる。', '塩・ごま油をふり、ラップをして電子レンジで加熱する。', '長ねぎを散らして完成。'], tips: ['もやしを下に敷くと蒸気が均一に通り火の通りが良くなる。', 'ラップはふんわりかけると蒸気がこもりすぎない。'] },
  { name: '卵とツナの中華炒め', genre: '中', time: 10, description: 'ツナの旨みを活かした手早い卵炒め。', need: ['egg', 'tuna_can', 'negi', 'sesame_oil', 'oyster_sauce'], steps: ['ツナ缶の油を軽く切る。', '卵を溶いてごま油で半熟に炒める。', 'ツナと長ねぎを加え、オイスターソースで味付けする。'], tips: ['ツナ缶の油は軽く切ってから使うと炒めがベタつかない。', '卵は半熟で取り出すとふんわり感が保てる。'] },
  { name: 'えのきの豚肉巻き中華風', genre: '中', time: 20, description: 'きのこの食感を豚肉で楽しむ一口おかず。', need: ['pork', 'mushroom', 'negi', 'soy_sauce', 'sesame_oil', 'katakuriko'], steps: ['きのこを豚肉で巻く。', 'フライパンで転がしながら焼き、火を通す。', '醤油・ごま油・水溶き片栗粉のタレを絡める。'], tips: ['巻き終わりを下にして焼くと型崩れしにくい。', '転がしながら焼くと全体に均一に火が通る。'] },
  { name: 'なすと豚肉の中華炒め', genre: '中', time: 20, description: 'なすが油と豆板醤の旨みを吸い込んだ炒め物。', need: ['nasu', 'pork', 'doubanjiang', 'oyster_sauce', 'garlic'], steps: ['なすを乱切りにし、豚肉と炒める。', 'にんにく・豆板醤を加えて香りを出す。', 'オイスターソースで味付けする。'], tips: ['なすは油をなじませてから炒めると色よく仕上がる。', '豆板醤は炒めて香りを出してから他の材料を加える。'] },
  { name: '豆腐と卵の中華スープ炒め', genre: '中', time: 20, description: 'とろみのあるスープと卵のやさしい口当たりが特徴。', need: ['tofu', 'egg', 'chuka_dashi', 'katakuriko', 'negi'], steps: ['豆腐を崩し、長ねぎを小口切りにする。', '中華だしで煮立て、豆腐を加える。', '溶き卵を回し入れ、水溶き片栗粉でとろみをつける。'], tips: ['豆腐は大きめに崩すと食感が楽しめる。', '卵は仕上げに回し入れ、固まりすぎる前に火を止める。'] },

  // ===== 洋食 30品 =====
  { name: 'ハンバーグ', genre: '洋', time: 30, description: '肉汁を閉じ込めてジューシーに焼き上げる洋食の代表格。', need: ['mixed_mince', 'egg', 'panko', 'onion', 'milk', 'ketchup', 'worcester', 'salt', 'pepper'], steps: ['玉ねぎをみじん切りにして炒め、冷ます。', '合いびき肉・卵・パン粉・牛乳・玉ねぎ・塩こしょうを混ぜて成形する。', 'フライパンで両面を焼き、蓋をして中まで火を通す。', 'ケチャップ・ウスターソースでソースを作りかける。'], tips: ['タネは冷やしてから成形すると崩れにくい。', '中央をくぼませて焼くと中心まで均一に火が通る。'] },
  { name: 'カレーライス', genre: '洋', time: 45, description: '野菜の甘みとスパイスが溶け合う日本の定番洋食。', need: ['pork', 'onion', 'carrot', 'potato', 'curry_roux', 'rice'], steps: ['豚肉・玉ねぎ・にんじん・じゃがいもを一口大に切る。', '鍋で炒めてから水を加えて煮込む。', '火を止めてカレールーを溶かし、とろみがつくまで煮込む。'], tips: ['野菜はしっかり炒めてから煮ると甘みが引き出される。', 'ルーは火を止めてから加えるとダマになりにくい。'] },
  { name: 'オムライス', genre: '洋', time: 20, description: 'ケチャップライスをふわとろ卵で包んだ人気メニュー。', need: ['egg', 'chicken', 'onion', 'ketchup', 'rice', 'butter'], steps: ['鶏肉・玉ねぎを炒め、ご飯とケチャップを加えてチキンライスを作る。', '卵を溶いてバターで薄焼き卵を焼く。', 'チキンライスを包み、皿に盛る。'], tips: ['卵は強火で手早く混ぜると半熟のふわとろに仕上がる。', 'フライパンを傾けながら形を整えるときれいに包める。'] },
  { name: 'ナポリタン', genre: '洋', time: 20, description: 'ケチャップの酸味とコクが懐かしい喫茶店風パスタ。', need: ['pasta', 'sausage', 'piman', 'onion', 'mushroom', 'ketchup', 'butter'], steps: ['パスタを表示通りに茹でる。', 'バターでウインナー・玉ねぎ・ピーマン・きのこを炒める。', '茹でたパスタとケチャップを加えて絡める。'], tips: ['パスタを少し柔らかめに茹でると具材と絡みやすい。', 'ケチャップは先に軽く炒めて酸味を飛ばすとコクが出る。'] },
  { name: 'ミートソースパスタ', genre: '洋', time: 30, description: 'じっくり煮込んだ濃厚なミートソースが絡むパスタ。', need: ['pasta', 'mixed_mince', 'tomato_can', 'onion', 'garlic', 'olive_oil', 'consomme'], steps: ['パスタを茹でる。', 'にんにく・玉ねぎを炒め、合いびき肉を加えて炒める。', 'トマト缶・コンソメを加えて煮込み、パスタに絡める。'], tips: ['ひき肉は強火で焼き付けるように炒めると旨みが増す。', '弱火でじっくり煮込むと味がまとまる。'] },
  { name: 'カルボナーラ', genre: '洋', time: 20, description: '卵とチーズのコクが濃厚な、火加減が決め手のパスタ。', need: ['pasta', 'bacon', 'egg', 'cheese', 'cream', 'pepper'], steps: ['パスタを茹でる。', 'ベーコンを炒める。', '卵・チーズ・生クリーム・こしょうを混ぜたソースにパスタとベーコンを絡める。'], tips: ['火を止めてから卵液を加えると固まらずクリーミーに仕上がる。', '茹で汁でソースの濃度を調整する。'] },
  { name: 'クリームシチュー', genre: '洋', time: 45, description: 'ホワイトソースの優しい甘みが染みる冬の定番。', need: ['chicken', 'onion', 'carrot', 'potato', 'milk', 'butter', 'flour', 'consomme'], steps: ['鶏肉・玉ねぎ・にんじん・じゃがいもを一口大に切って炒める。', '水とコンソメを加えて煮込む。', 'バター・小麦粉を炒めたルーと牛乳を加え、とろみがつくまで煮る。'], tips: ['ルーは焦がさないよう弱火でじっくり炒める。', '牛乳は少しずつ加えるとダマになりにくい。'] },
  { name: 'ビーフシチュー', genre: '洋', time: 45, description: '牛肉を長時間煮込んでとろける柔らかさに仕上げた一品。', need: ['beef', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme', 'butter'], steps: ['牛肉・玉ねぎ・にんじん・じゃがいもを一口大に切って炒める。', 'トマト缶とコンソメ、水を加えて煮込む。', 'バターを加えて風味を整え、とろみが出るまで煮詰める。'], tips: ['牛肉は最初に強火で表面を焼き固めると旨みが閉じ込められる。', '弱火でじっくり煮込むほど肉が柔らかくなる。'] },
  { name: 'コロッケ', genre: '洋', time: 45, description: 'サクサクの衣とほくほくのじゃがいもが楽しい揚げ物。', need: ['potato', 'mixed_mince', 'onion', 'panko', 'egg', 'flour', 'oil'], steps: ['じゃがいもを茹でて潰す。', '合いびき肉・玉ねぎを炒め、じゃがいもと混ぜて成形する。', '小麦粉・卵・パン粉の順につけ、油で揚げる。'], tips: ['生地は冷ましてから成形すると崩れにくい。', '衣は少し休ませてから揚げると剥がれにくい。'] },
  { name: 'チキンソテー', genre: '洋', time: 20, description: '皮目をパリッと焼き上げるシンプルな鶏肉料理。', need: ['chicken', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'], steps: ['鶏肉に塩こしょうする。', 'オリーブオイルとにんにくでフライパンを香りづけする。', '皮目からじっくり焼き、バターを絡めて仕上げる。'], tips: ['皮目を重しをして焼くと均一にパリッと仕上がる。', '焼いたあと少し休ませると肉汁が落ち着く。'] },
  { name: 'ポークソテー', genre: '洋', time: 20, description: '香ばしく焼いた豚肉にバターのコクを効かせた一品。', need: ['pork', 'garlic', 'olive_oil', 'salt', 'pepper', 'butter'], steps: ['豚肉に塩こしょうし、筋切りする。', 'オリーブオイルとにんにくで香りをつける。', '両面を焼き、バターを絡めて仕上げる。'], tips: ['筋切りをすると加熱時に肉が縮まない。', '焼く直前に室温に戻すと均一に火が通る。'] },
  { name: 'ハヤシライス', genre: '洋', time: 30, description: 'トマトの酸味とデミグラス風の濃厚さが特徴の洋食丼。', need: ['beef', 'onion', 'tomato_can', 'ketchup', 'consomme', 'butter', 'rice'], steps: ['牛肉・玉ねぎを炒める。', 'トマト缶・ケチャップ・コンソメを加えて煮込む。', 'バターでコクを出し、ご飯にかける。'], tips: ['玉ねぎをじっくり炒めると甘みとコクが増す。', '煮込みすぎず牛肉を柔らかいうちに仕上げる。'] },
  { name: 'ロールキャベツ', genre: '洋', time: 45, description: 'キャベツの甘みと肉だねの旨みが溶け合う煮込み料理。', need: ['cabbage', 'mixed_mince', 'onion', 'consomme', 'tomato_can'], steps: ['キャベツを柔らかく茹でる。', '合いびき肉・玉ねぎを混ぜてキャベツで巻く。', 'コンソメとトマト缶のスープで煮込む。'], tips: ['キャベツは芯を薄くそぐと巻きやすくなる。', '巻き終わりを下にして煮ると型崩れしにくい。'] },
  { name: 'グラタン', genre: '洋', time: 30, description: 'ホワイトソースとチーズの香ばしい焼き色が魅力の一品。', need: ['chicken', 'onion', 'mushroom', 'milk', 'butter', 'flour', 'cheese', 'panko'], steps: ['鶏肉・玉ねぎ・きのこを炒める。', 'バター・小麦粉・牛乳でホワイトソースを作り、具と合わせる。', '耐熱皿に入れチーズとパン粉をのせてオーブンで焼く。'], tips: ['ソースは少しゆるめに仕上げると焼いたときにちょうど良い濃度になる。', 'チーズは表面全体を覆うと焼きムラができにくい。'] },
  { name: 'ドリア', genre: '洋', time: 30, description: 'ケチャップライスとホワイトソースの組み合わせが人気の一品。', need: ['rice', 'chicken', 'onion', 'milk', 'butter', 'flour', 'cheese', 'ketchup'], steps: ['ご飯にケチャップを混ぜて耐熱皿に敷く。', '鶏肉・玉ねぎを炒め、バター・小麦粉・牛乳でホワイトソースを作る。', 'ご飯にソースをかけ、チーズをのせて焼く。'], tips: ['ご飯は薄く均一に敷くと味のムラが出にくい。', '焼く直前にチーズをたっぷりのせると香ばしく仕上がる。'] },
  { name: 'フライドチキン', genre: '洋', time: 30, description: 'スパイシーな衣でカリッと揚げた食べ応えのある一品。', need: ['chicken', 'flour', 'egg', 'panko', 'salt', 'pepper', 'oil'], steps: ['鶏肉に塩こしょうで下味をつける。', '小麦粉・卵・パン粉の順に衣をつける。', '油できつね色になるまで揚げる。'], tips: ['二度揚げすると中まで火が通りつつ衣がカリッとする。', '衣をつけたら少し置くと剥がれにくくなる。'] },
  { name: 'ポトフ', genre: '洋', time: 30, description: '野菜の旨みが溶け込んだ、じっくり煮込むフランスの家庭料理。', need: ['sausage', 'cabbage', 'carrot', 'potato', 'onion', 'consomme'], steps: ['ウインナー・キャベツ・にんじん・じゃがいも・玉ねぎを大きめに切る。', '鍋に材料と水、コンソメを入れて煮込む。', '野菜が柔らかくなるまでじっくり煮る。'], tips: ['弱火でコトコト煮ると野菜の甘みが引き出される。', 'アクをこまめに取るとスープが澄んで美味しくなる。'] },
  { name: 'トマトとチーズのオムレツ', genre: '洋', time: 10, description: 'トマトの酸味とチーズのコクが絡み合う卵料理。', need: ['egg', 'tomato', 'cheese', 'milk', 'salt', 'pepper', 'butter'], steps: ['トマトを角切りにする。', '卵に牛乳・塩こしょうを混ぜる。', 'バターで卵を焼き、トマトとチーズを包んで仕上げる。'], tips: ['卵は強火で手早く混ぜると柔らかい食感に仕上がる。', '具は加熱しすぎず卵の中に軽く包む程度にする。'] },
  { name: 'ツナとトマトのパスタ', genre: '洋', time: 20, description: 'ツナの旨みとトマトの酸味が手軽に楽しめるパスタ。', need: ['pasta', 'tuna_can', 'tomato_can', 'garlic', 'olive_oil'], steps: ['パスタを茹でる。', 'にんにくをオリーブオイルで炒め、トマト缶とツナを加えて煮る。', 'パスタと絡める。'], tips: ['にんにくは弱火でじっくり香りを引き出す。', 'ツナの油も少し使うとコクが増す。'] },
  { name: 'きのこのクリームパスタ', genre: '洋', time: 20, description: 'きのこの旨みと生クリームのコクが絡み合うパスタ。', need: ['pasta', 'mushroom', 'bacon', 'cream', 'butter', 'consomme', 'cheese'], steps: ['パスタを茹でる。', 'ベーコンときのこをバターで炒める。', '生クリーム・コンソメ・チーズを加えてソースを作り、パスタと絡める。'], tips: ['きのこは強火で焼き付けるように炒めると旨みが増す。', 'ソースは煮詰めすぎず、茹で汁で濃度を調整する。'] },
  { name: 'ペペロンチーノ', genre: '洋', time: 10, description: 'にんにくの香りとオリーブオイルのコクだけで仕上げるシンプルパスタ。', need: ['pasta', 'garlic', 'olive_oil', 'salt', 'pepper'], steps: ['パスタを茹でる。', 'オリーブオイルでにんにくをじっくり熱して香りを出す。', '茹で汁少々とパスタを加えて塩こしょうで仕上げる。'], tips: ['にんにくは弱火でじっくり色づける程度に加熱する。', '茹で汁を加えて乳化させるとソースがパスタに絡みやすくなる。'] },
  { name: 'ジャーマンポテト', genre: '洋', time: 20, description: 'じゃがいもとウインナーを香ばしく焼いたドイツ風の一品。', need: ['potato', 'sausage', 'onion', 'butter', 'salt', 'pepper'], steps: ['じゃがいもを一口大に切って下茹でする。', 'バターでウインナー・玉ねぎを炒める。', 'じゃがいもを加えて焼き色をつけ、塩こしょうで味を調える。'], tips: ['じゃがいもは下茹でしてから焼くと外はカリッと中はほくほくに仕上がる。', '触りすぎず焼き付けると焼き色がきれいにつく。'] },
  { name: 'きのこのアヒージョ', genre: '洋', time: 10, description: 'オリーブオイルでじっくり煮るスペイン風の前菜。', need: ['mushroom', 'garlic', 'olive_oil', 'salt', 'pepper'], steps: ['きのこを食べやすく切る。', 'オリーブオイルとにんにくを弱火で熱する。', 'きのこを加えて煮るように火を通し、塩こしょうで味を調える。'], tips: ['にんにくは低温からじっくり加熱して香りを引き出す。', 'きのこは種類を混ぜると旨みと食感に変化が出る。'] },
  { name: 'キッシュ', genre: '洋', time: 45, description: '卵とクリームの生地に具材を閉じ込めたフランスの家庭料理。', need: ['egg', 'bacon', 'onion', 'cheese', 'cream', 'flour', 'butter'], steps: ['ベーコン・玉ねぎを炒める。', '卵・生クリーム・チーズを混ぜて具と合わせる。', '型に入れ、小麦粉を使った生地とともにオーブンで焼く。'], tips: ['具材の水分をしっかり飛ばしてから生地に加える。', '焼く前に生地を冷やすと焼き縮みしにくい。'] },
  { name: 'ラザニア', genre: '洋', time: 45, description: 'ミートソースとホワイトソースを層にして焼き上げる一品。', need: ['pasta', 'mixed_mince', 'tomato_can', 'cheese', 'milk', 'flour', 'butter'], steps: ['パスタ（ラザニア用）を茹でる。', '合いびき肉・トマト缶でミートソースを作る。', 'バター・小麦粉・牛乳でホワイトソースを作り、パスタと交互に重ねてチーズをのせて焼く。'], tips: ['ソースは少しゆるめに作ると層になじみやすい。', '焼く前に少し休ませると層が安定して切り分けやすい。'] },
  { name: 'チーズハンバーグ', genre: '洋', time: 30, description: '中からとろけるチーズが楽しいハンバーグ。', need: ['mixed_mince', 'egg', 'panko', 'onion', 'cheese', 'ketchup'], steps: ['玉ねぎをみじん切りにして炒める。', '合いびき肉・卵・パン粉・玉ねぎを混ぜ、チーズを包んで成形する。', '焼いてケチャップソースをかける。'], tips: ['チーズはタネの中心にしっかり包み込むと流れ出にくい。', '中火でじっくり焼き、蓋をして蒸し焼きにする。'] },
  { name: 'ビーフストロガノフ', genre: '洋', time: 30, description: '牛肉ときのこを生クリームでまろやかに仕上げたロシア料理。', need: ['beef', 'onion', 'mushroom', 'cream', 'consomme', 'butter'], steps: ['牛肉・玉ねぎ・きのこを炒める。', 'コンソメと水を加えて煮込む。', '生クリームとバターを加えてまろやかに仕上げる。'], tips: ['牛肉は強火でさっと焼き付けて硬くなりすぎないようにする。', '生クリームは煮立たせすぎないよう仕上げに加える。'] },
  { name: 'ミネストローネ風煮込み', genre: '洋', time: 30, description: '野菜の旨みがぎゅっと詰まったトマトベースの煮込み。', need: ['bacon', 'onion', 'carrot', 'potato', 'tomato_can', 'consomme'], steps: ['ベーコン・玉ねぎ・にんじん・じゃがいもを炒める。', 'トマト缶と水、コンソメを加えて煮込む。', '野菜が柔らかくなるまで煮る。'], tips: ['野菜は大きさを揃えて切ると火の通りが均一になる。', '弱火でじっくり煮ると味がなじむ。'] },
  { name: 'ツナグラタン', genre: '洋', time: 30, description: 'ツナの旨みとホワイトソースが絡む手軽なグラタン。', need: ['tuna_can', 'onion', 'milk', 'butter', 'flour', 'cheese', 'panko'], steps: ['玉ねぎを炒め、ツナを加える。', 'バター・小麦粉・牛乳でホワイトソースを作り、具と合わせる。', '耐熱皿に入れてチーズとパン粉をのせて焼く。'], tips: ['ツナは油を軽く切ってから使うとソースがゆるくならない。', '焼く直前にチーズをのせると香ばしさが増す。'] },
  { name: 'ウインナーのケチャップ炒め', genre: '洋', time: 10, description: '子どもにも人気の甘酸っぱいケチャップ炒め。', need: ['sausage', 'piman', 'onion', 'ketchup'], steps: ['ウインナーに切り込みを入れる。', '玉ねぎ・ピーマンとともに炒める。', 'ケチャップを加えて絡める。'], tips: ['ウインナーに切り込みを入れると味が染みやすく見た目も可愛くなる。', 'ケチャップは焦げやすいので弱めの火で絡める。'] },

  // ===== 他 10品 =====
  { name: 'ガパオライス', genre: '他', time: 20, description: 'バジルの香りとオイスターソースの旨みが効いたタイ風炒めご飯。', need: ['pork_mince', 'piman', 'onion', 'garlic', 'oyster_sauce', 'soy_sauce', 'sugar', 'egg', 'rice'], steps: ['にんにく・玉ねぎ・ピーマンを炒める。', 'ひき肉を加えて炒め、オイスターソース・醤油・砂糖で味付けする。', '目玉焼きをのせてご飯と一緒に盛る。'], tips: ['ひき肉は強火で一気に炒めるとパラッと仕上がる。', '目玉焼きは半熟にすると黄身がソース代わりになる。'] },
  { name: 'ビビンバ', genre: '他', time: 30, description: '彩り野菜とナムルを混ぜて食べる韓国の定番丼。', need: ['beef', 'moyashi', 'carrot', 'spinach_frozen', 'egg', 'soy_sauce', 'sesame_oil', 'garlic', 'rice'], steps: ['牛肉を炒めて醤油・砂糖・ごま油・にんにくで味付けする。', 'もやし・にんじん・ほうれん草をそれぞれナムル風に和える。', 'ご飯に具材と卵をのせて盛りつける。'], tips: ['具材はそれぞれ別に調理すると味がぼやけない。', '熱々のご飯にのせるとナムルの香りが引き立つ。'] },
  { name: 'プルコギ', genre: '他', time: 20, description: '甘辛いタレに漬け込んだ牛肉を焼く韓国の焼肉料理。', need: ['beef', 'onion', 'negi', 'soy_sauce', 'sugar', 'sesame_oil', 'garlic'], steps: ['牛肉を醤油・砂糖・ごま油・にんにくで下味をつける。', '玉ねぎ・長ねぎとともにフライパンで炒める。', '汁気が飛ぶまで炒めて仕上げる。'], tips: ['肉は下味に漬け込む時間を長くするほど味が染み込む。', '強火で汁気を飛ばすように炒めると香ばしく仕上がる。'] },
  { name: 'タコライス', genre: '他', time: 20, description: 'メキシカン風味のひき肉をご飯にのせた沖縄生まれの一品。', need: ['mixed_mince', 'cheese', 'tomato', 'lettuce', 'ketchup', 'consomme', 'rice'], steps: ['合いびき肉を炒め、ケチャップとコンソメで味付けする。', 'ご飯の上に肉・レタス・トマト・チーズをのせる。'], tips: ['ひき肉はしっかり水分を飛ばして炒めるとご飯と絡みやすい。', '野菜は食べる直前にのせるとシャキシャキ感が残る。'] },
  { name: 'チリコンカン', genre: '他', time: 45, description: 'スパイスとトマトの酸味が効いたひき肉の煮込み。', need: ['mixed_mince', 'tomato_can', 'onion', 'garlic', 'consomme'], steps: ['合いびき肉・玉ねぎ・にんにくを炒める。', 'トマト缶とコンソメを加えて煮込む。', '汁気がなじむまでじっくり煮込む。'], tips: ['じっくり煮込むほどスパイスの風味がなじむ。', '仕上げに酸味を少し足すと味が締まる。'] },
  { name: 'ヤンニョムチキン', genre: '他', time: 30, description: '甘辛いタレを絡めた韓国風の揚げ鶏。', need: ['chicken', 'ketchup', 'garlic', 'sugar', 'soy_sauce', 'oil'], steps: ['鶏肉を揚げ焼きにする。', 'ケチャップ・にんにく・砂糖・醤油を煮立ててタレを作る。', '鶏肉にタレを絡める。'], tips: ['揚げたてにタレを絡めると衣がべたつきにくい。', 'タレは煮詰めてとろみをつけると絡みが良くなる。'] },
  { name: 'カオマンガイ', genre: '他', time: 30, description: '鶏の旨みを吸ったご飯とたれが絶妙なタイ料理。', need: ['chicken', 'rice', 'garlic', 'ginger', 'soy_sauce', 'sesame_oil'], steps: ['米と鶏肉、にんにく・しょうがを一緒に炊く。', '鶏肉を取り出して食べやすく切る。', '醤油・ごま油のたれをかけてご飯と一緒に盛る。'], tips: ['鶏肉と一緒に米を炊くと旨みがご飯全体に行き渡る。', '蒸らし時間をしっかり取るとご飯がふっくら仕上がる。'] },
  { name: 'エスニック風鶏肉炒め', genre: '他', time: 20, description: 'オイスターソースとごま油で仕上げる無国籍風炒め物。', need: ['chicken', 'piman', 'onion', 'oyster_sauce', 'garlic', 'sesame_oil'], steps: ['鶏肉とピーマン・玉ねぎを一口大に切る。', 'にんにくを炒めて香りを出し、鶏肉を加える。', 'ピーマン・玉ねぎを加え、オイスターソース・ごま油で味付けする。'], tips: ['鶏肉はそぎ切りにすると火が通りやすく柔らかい。', '野菜は強火で手早く炒め食感を残す。'] },
  { name: 'アジアン風豚肉と野菜の炒め物', genre: '他', time: 20, description: 'オイスターソースの旨みが野菜と豚肉に絡む炒め物。', need: ['pork', 'cabbage', 'carrot', 'oyster_sauce', 'garlic', 'sesame_oil'], steps: ['豚肉とキャベツ・にんじんを食べやすく切る。', 'にんにくを炒めて豚肉を加える。', '野菜を加えて炒め、オイスターソース・ごま油で味付けする。'], tips: ['野菜は大きさを揃えて切ると火の通りが均一になる。', '強火で一気に炒めると水っぽくならない。'] },
  { name: 'カレー風味の卵と厚揚げ炒め', genre: '他', time: 10, description: 'カレー粉のスパイシーな香りを効かせた炒め物。', need: ['egg', 'atsuage', 'curry_roux', 'onion', 'soy_sauce'], steps: ['厚揚げを一口大に切り、玉ねぎを薄切りにする。', 'フライパンで炒め、カレールーを少量溶かし入れる。', '溶き卵を加えて絡め、醤油で味を調える。'], tips: ['カレールーは少量を溶かし入れると程よい風味になる。', '卵は半熟で火を止めるとふんわり仕上がる。'] },
];
