// 千歳烏山駅 京王線 下り(新宿方面)時刻表データ
// 出典: 京王電鉄 発車標準時刻表(2026年8月17日改正)をもとにユーザーが書き起こしたデータ
// 土休日ダイヤは未取得のため未対応(平日データのみ)

// 千歳烏山→新宿(または新宿方面の起点となる新線新宿)の所要時分(分)
// 特急12分・区間急行14分は複数の乗換案内サイトで確認済み。
// 急行はこの区間で区間急行と同じ停車駅パターン(桜上水にも停車)のため、
// 区間急行と同じ14分と仮定している(要確認)。
const DURATION_MIN = {
  tokkyu: 12,
  kyuko: 14,
  kukan_kyuko: 14,
  kaisoku: 20,
  kakutei: 20,
};

const TYPE_LABEL = {
  tokkyu: '特急',
  kyuko: '急行',
  kukan_kyuko: '区間急行',
  kaisoku: '快速',
  kakutei: '各停',
};

// 種別ごとの表示用の強さ(速達性が高いほど大きい値。バッジの色分けに利用)
const TYPE_RANK = {
  tokkyu: 5,
  kyuko: 4,
  kukan_kyuko: 3,
  kaisoku: 2,
  kakutei: 1,
};

const DEST_LABEL = {
  shinjuku: '新宿',
  shinsen_shinjuku: '新線新宿',
  motoyawata: '本八幡',
  oshima: '大島',
  sakurajosui: '桜上水',
};

// dest が sakurajosui の電車は千歳烏山と新宿の間で運行を終える(桜上水止まり)ため、
// 新宿へは直通しない。一覧・比較の対象からは除外する。
const NOT_REACHING_SHINJUKU = new Set(['sakurajosui']);

// [発車時刻(HH:MM), 種別, 行き先]
const WEEKDAY_RAW = [
  ['04:55', 'kakutei', 'shinsen_shinjuku'],
  ['05:10', 'tokkyu', 'shinjuku'],
  ['05:12', 'kakutei', 'shinjuku'],
  ['05:15', 'kaisoku', 'motoyawata'],
  ['05:29', 'tokkyu', 'shinjuku'],
  ['05:32', 'kakutei', 'shinjuku'],
  ['05:34', 'kukan_kyuko', 'shinjuku'],
  ['05:47', 'kakutei', 'shinjuku'],
  ['05:50', 'tokkyu', 'shinjuku'],
  ['05:56', 'kukan_kyuko', 'shinjuku'],
  ['05:58', 'kakutei', 'shinjuku'],
  ['06:01', 'kakutei', 'shinjuku'],
  ['06:11', 'tokkyu', 'shinjuku'],
  ['06:14', 'kakutei', 'shinjuku'],
  ['06:19', 'kukan_kyuko', 'shinjuku'],
  ['06:23', 'tokkyu', 'shinjuku'],
  ['06:25', 'kakutei', 'motoyawata'],
  ['06:27', 'kukan_kyuko', 'shinjuku'],
  ['06:29', 'tokkyu', 'shinjuku'],
  ['06:32', 'kakutei', 'shinjuku'],
  ['06:35', 'tokkyu', 'shinjuku'],
  ['06:38', 'kukan_kyuko', 'motoyawata'],
  ['06:41', 'tokkyu', 'shinjuku'],
  ['06:43', 'kakutei', 'motoyawata'],
  ['06:47', 'kukan_kyuko', 'motoyawata'],
  ['06:52', 'tokkyu', 'shinjuku'],
  ['06:54', 'kakutei', 'shinjuku'],
  ['06:56', 'tokkyu', 'shinjuku'],
  ['06:59', 'kukan_kyuko', 'motoyawata'],
  ['07:02', 'kakutei', 'shinjuku'],
  ['07:04', 'tokkyu', 'shinjuku'],
  ['07:06', 'kakutei', 'motoyawata'],
  ['07:08', 'kukan_kyuko', 'motoyawata'],
  ['07:10', 'tokkyu', 'shinjuku'],
  ['07:14', 'kakutei', 'shinjuku'],
  ['07:17', 'kukan_kyuko', 'shinjuku'],
  ['07:19', 'tokkyu', 'shinjuku'],
  ['07:22', 'kakutei', 'shinjuku'],
  ['07:24', 'kukan_kyuko', 'motoyawata'],
  ['07:27', 'tokkyu', 'shinjuku'],
  ['07:29', 'kakutei', 'shinjuku'],
  ['07:31', 'kyuko', 'shinjuku'],
  ['07:33', 'kakutei', 'shinjuku'],
  ['07:36', 'kukan_kyuko', 'motoyawata'],
  ['07:38', 'kyuko', 'shinjuku'],
  ['07:41', 'kakutei', 'shinjuku'],
  ['07:44', 'kukan_kyuko', 'motoyawata'],
  ['07:46', 'kukan_kyuko', 'shinjuku'],
  ['07:48', 'kakutei', 'shinjuku'],
  ['07:50', 'kukan_kyuko', 'shinjuku'],
  ['07:52', 'kakutei', 'shinjuku'],
  ['07:54', 'kyuko', 'motoyawata'],
  ['07:56', 'kakutei', 'shinjuku'],
  ['07:58', 'kukan_kyuko', 'shinjuku'],
  ['08:01', 'kyuko', 'shinjuku'],
  ['08:03', 'kakutei', 'shinjuku'],
  ['08:05', 'kukan_kyuko', 'motoyawata'],
  ['08:07', 'tokkyu', 'shinjuku'],
  ['08:09', 'kakutei', 'motoyawata'],
  ['08:12', 'tokkyu', 'shinjuku'],
  ['08:14', 'kakutei', 'shinjuku'],
  ['08:16', 'kyuko', 'shinjuku'],
  ['08:18', 'kakutei', 'shinjuku'],
  ['08:21', 'kukan_kyuko', 'shinjuku'],
  ['08:24', 'tokkyu', 'shinjuku'],
  ['08:26', 'kakutei', 'oshima'],
  ['08:29', 'kukan_kyuko', 'oshima'],
  ['08:31', 'tokkyu', 'shinjuku'],
  ['08:34', 'kakutei', 'shinjuku'],
  ['08:36', 'kyuko', 'shinjuku'],
  ['08:38', 'kakutei', 'shinjuku'],
  ['08:40', 'tokkyu', 'shinjuku'],
  ['08:42', 'kakutei', 'shinjuku'],
  ['08:44', 'kukan_kyuko', 'oshima'],
  ['08:48', 'tokkyu', 'shinjuku'],
  ['08:51', 'kakutei', 'motoyawata'],
  ['08:52', 'kyuko', 'shinjuku'],
  ['08:56', 'tokkyu', 'shinjuku'],
  ['08:58', 'kakutei', 'shinjuku'],
  ['09:00', 'kukan_kyuko', 'motoyawata'],
  ['09:05', 'tokkyu', 'shinjuku'],
  ['09:08', 'kukan_kyuko', 'oshima'],
  ['09:09', 'kakutei', 'shinjuku'],
  ['09:12', 'tokkyu', 'shinjuku'],
  ['09:15', 'kaisoku', 'oshima'],
  ['09:18', 'kakutei', 'shinjuku'],
  ['09:22', 'tokkyu', 'shinjuku'],
  ['09:25', 'kaisoku', 'shinjuku'],
  ['09:27', 'kakutei', 'shinjuku'],
  ['09:33', 'tokkyu', 'shinjuku'],
  ['09:36', 'kukan_kyuko', 'oshima'],
  ['09:38', 'kakutei', 'shinjuku'],
  ['09:42', 'tokkyu', 'shinjuku'],
  ['09:44', 'kaisoku', 'motoyawata'],
  ['09:46', 'tokkyu', 'shinjuku'],
  ['09:48', 'kakutei', 'shinjuku'],
  ['09:52', 'tokkyu', 'shinjuku'],
  ['09:56', 'kukan_kyuko', 'motoyawata'],
  ['09:58', 'kakutei', 'shinjuku'],
  ['10:00', 'tokkyu', 'shinjuku'],
  ['10:05', 'kaisoku', 'motoyawata'],
  ['10:07', 'kakutei', 'shinjuku'],
  ['10:09', 'tokkyu', 'shinjuku'],
  ['10:11', 'tokkyu', 'shinjuku'],
  ['10:14', 'kaisoku', 'motoyawata'],
  ['10:17', 'kakutei', 'shinjuku'],
  ['10:20', 'tokkyu', 'shinjuku'],
  ['10:22', 'tokkyu', 'shinjuku'],
  ['10:26', 'kukan_kyuko', 'motoyawata'],
  ['10:27', 'kakutei', 'shinjuku'],
  ['10:30', 'tokkyu', 'shinjuku'],
  ['10:34', 'kaisoku', 'motoyawata'],
  ['10:37', 'kakutei', 'shinjuku'],
  ['10:40', 'tokkyu', 'shinjuku'],
  ['10:42', 'tokkyu', 'shinjuku'],
  ['10:46', 'kukan_kyuko', 'motoyawata'],
  ['10:47', 'kakutei', 'shinjuku'],
  ['10:51', 'tokkyu', 'shinjuku'],
  ['10:54', 'kaisoku', 'motoyawata'],
  ['10:56', 'kakutei', 'shinjuku'],
];

// 11時台〜15時台は日中パターンとして同一(ユーザー提供データより)。
// 誤入力を避けるため、1時間分をテンプレート化して各時間へ展開する。
const DAYTIME_PATTERN_TEMPLATE = [
  ['00', 'tokkyu', 'shinjuku'],
  ['02', 'tokkyu', 'shinjuku'],
  ['06', 'kukan_kyuko', 'motoyawata'],
  ['07', 'kakutei', 'shinjuku'],
  ['11', 'tokkyu', 'shinjuku'],
  ['14', 'kaisoku', 'motoyawata'],
  ['16', 'kakutei', 'shinjuku'],
  ['20', 'tokkyu', 'shinjuku'],
  ['22', 'tokkyu', 'shinjuku'],
  ['26', 'kukan_kyuko', 'motoyawata'],
  ['27', 'kakutei', 'shinjuku'],
  ['31', 'tokkyu', 'shinjuku'],
  ['34', 'kaisoku', 'motoyawata'],
  ['36', 'kakutei', 'shinjuku'],
  ['40', 'tokkyu', 'shinjuku'],
  ['42', 'tokkyu', 'shinjuku'],
  ['46', 'kukan_kyuko', 'motoyawata'],
  ['47', 'kakutei', 'shinjuku'],
  ['51', 'tokkyu', 'shinjuku'],
  ['54', 'kaisoku', 'motoyawata'],
  ['56', 'kakutei', 'shinjuku'],
];
for (const hour of [11, 12, 13, 14, 15]) {
  for (const [min, type, dest] of DAYTIME_PATTERN_TEMPLATE) {
    WEEKDAY_RAW.push([`${String(hour).padStart(2, '0')}:${min}`, type, dest]);
  }
}

WEEKDAY_RAW.push(
  ['16:00', 'tokkyu', 'shinjuku'],
  ['16:02', 'tokkyu', 'shinjuku'],
  ['16:06', 'kukan_kyuko', 'motoyawata'],
  ['16:07', 'kakutei', 'shinjuku'],
  ['16:11', 'tokkyu', 'shinjuku'],
  ['16:14', 'kukan_kyuko', 'motoyawata'],
  ['16:18', 'kakutei', 'shinjuku'],
  ['16:20', 'tokkyu', 'shinjuku'],
  ['16:23', 'kaisoku', 'motoyawata'],
  ['16:26', 'kakutei', 'shinjuku'],
  ['16:30', 'tokkyu', 'shinjuku'],
  ['16:32', 'tokkyu', 'shinjuku'],
  ['16:36', 'kukan_kyuko', 'motoyawata'],
  ['16:37', 'kakutei', 'shinjuku'],
  ['16:41', 'tokkyu', 'shinjuku'],
  ['16:44', 'kukan_kyuko', 'motoyawata'],
  ['16:46', 'kyuko', 'shinjuku'],
  ['16:48', 'kakutei', 'shinjuku'],
  ['16:51', 'tokkyu', 'shinjuku'],
  ['16:55', 'kaisoku', 'motoyawata'],
  ['16:58', 'kakutei', 'shinjuku'],

  ['17:01', 'tokkyu', 'shinjuku'],
  ['17:04', 'kaisoku', 'motoyawata'],
  ['17:06', 'tokkyu', 'shinjuku'],
  ['17:08', 'kakutei', 'shinjuku'],
  ['17:11', 'tokkyu', 'shinjuku'],
  ['17:14', 'kukan_kyuko', 'motoyawata'],
  ['17:17', 'kakutei', 'shinjuku'],
  ['17:20', 'tokkyu', 'shinjuku'],
  ['17:24', 'kaisoku', 'motoyawata'],
  ['17:26', 'tokkyu', 'shinjuku'],
  ['17:28', 'kakutei', 'shinjuku'],
  ['17:32', 'tokkyu', 'shinjuku'],
  ['17:35', 'kukan_kyuko', 'motoyawata'],
  ['17:37', 'kaisoku', 'shinjuku'],
  ['17:38', 'kakutei', 'shinjuku'],
  ['17:43', 'tokkyu', 'shinjuku'],
  ['17:46', 'kyuko', 'shinjuku'],
  ['17:47', 'kakutei', 'shinjuku'],
  ['17:50', 'kukan_kyuko', 'motoyawata'],
  ['17:53', 'tokkyu', 'shinjuku'],
  ['17:56', 'kukan_kyuko', 'motoyawata'],
  ['17:58', 'kakutei', 'shinjuku'],

  ['18:03', 'tokkyu', 'shinjuku'],
  ['18:06', 'kyuko', 'motoyawata'],
  ['18:08', 'kakutei', 'shinjuku'],
  ['18:13', 'tokkyu', 'shinjuku'],
  ['18:15', 'kyuko', 'shinjuku'],
  ['18:17', 'kakutei', 'shinjuku'],
  ['18:19', 'kukan_kyuko', 'motoyawata'],
  ['18:23', 'tokkyu', 'shinjuku'],
  ['18:25', 'kyuko', 'motoyawata'],
  ['18:28', 'kakutei', 'shinjuku'],
  ['18:33', 'tokkyu', 'shinjuku'],
  ['18:35', 'kyuko', 'shinjuku'],
  ['18:37', 'kakutei', 'shinjuku'],
  ['18:39', 'kukan_kyuko', 'motoyawata'],
  ['18:43', 'tokkyu', 'shinjuku'],
  ['18:46', 'kyuko', 'motoyawata'],
  ['18:48', 'kakutei', 'shinjuku'],
  ['18:53', 'tokkyu', 'shinjuku'],
  ['18:55', 'kyuko', 'shinjuku'],
  ['18:57', 'kakutei', 'shinjuku'],
  ['18:59', 'kukan_kyuko', 'motoyawata'],

  ['19:03', 'tokkyu', 'shinjuku'],
  ['19:06', 'kyuko', 'motoyawata'],
  ['19:08', 'kakutei', 'shinjuku'],
  ['19:13', 'tokkyu', 'shinjuku'],
  ['19:15', 'kyuko', 'shinjuku'],
  ['19:17', 'kakutei', 'shinjuku'],
  ['19:19', 'kukan_kyuko', 'motoyawata'],
  ['19:22', 'tokkyu', 'shinjuku'],
  ['19:25', 'kyuko', 'motoyawata'],
  ['19:28', 'kakutei', 'shinjuku'],
  ['19:33', 'tokkyu', 'shinjuku'],
  ['19:34', 'kyuko', 'shinjuku'],
  ['19:37', 'kakutei', 'shinjuku'],
  ['19:39', 'kukan_kyuko', 'motoyawata'],
  ['19:43', 'tokkyu', 'shinjuku'],
  ['19:46', 'kyuko', 'motoyawata'],
  ['19:48', 'kakutei', 'sakurajosui'],
  ['19:53', 'tokkyu', 'shinjuku'],
  ['19:55', 'kyuko', 'shinjuku'],
  ['19:58', 'kakutei', 'shinjuku'],

  ['20:00', 'kukan_kyuko', 'motoyawata'],
  ['20:03', 'tokkyu', 'shinjuku'],
  ['20:06', 'kyuko', 'motoyawata'],
  ['20:08', 'kakutei', 'shinjuku'],
  ['20:13', 'tokkyu', 'shinjuku'],
  ['20:15', 'kyuko', 'shinjuku'],
  ['20:17', 'kakutei', 'shinjuku'],
  ['20:20', 'kukan_kyuko', 'motoyawata'],
  ['20:24', 'tokkyu', 'shinjuku'],
  ['20:27', 'kukan_kyuko', 'motoyawata'],
  ['20:28', 'kakutei', 'shinjuku'],
  ['20:33', 'tokkyu', 'shinjuku'],
  ['20:35', 'kyuko', 'shinjuku'],
  ['20:37', 'kakutei', 'shinjuku'],
  ['20:39', 'kukan_kyuko', 'motoyawata'],
  ['20:43', 'tokkyu', 'shinjuku'],
  ['20:47', 'kukan_kyuko', 'motoyawata'],
  ['20:48', 'kakutei', 'shinjuku'],
  ['20:53', 'tokkyu', 'shinjuku'],
  ['20:54', 'kyuko', 'shinjuku'],
  ['20:57', 'kakutei', 'shinjuku'],
  ['20:59', 'kukan_kyuko', 'motoyawata'],

  ['21:04', 'tokkyu', 'shinjuku'],
  ['21:07', 'kukan_kyuko', 'motoyawata'],
  ['21:08', 'kakutei', 'shinjuku'],
  ['21:13', 'tokkyu', 'shinjuku'],
  ['21:15', 'kyuko', 'shinjuku'],
  ['21:17', 'kakutei', 'shinjuku'],
  ['21:20', 'kukan_kyuko', 'motoyawata'],
  ['21:24', 'tokkyu', 'shinjuku'],
  ['21:27', 'kukan_kyuko', 'motoyawata'],
  ['21:29', 'kakutei', 'shinjuku'],
  ['21:34', 'tokkyu', 'shinjuku'],
  ['21:37', 'kukan_kyuko', 'motoyawata'],
  ['21:40', 'kakutei', 'shinjuku'],
  ['21:45', 'tokkyu', 'shinjuku'],
  ['21:48', 'kaisoku', 'motoyawata'],
  ['21:50', 'kakutei', 'shinjuku'],
  ['21:59', 'kakutei', 'shinjuku'],

  ['22:01', 'kyuko', 'shinjuku'],
  ['22:08', 'kakutei', 'shinjuku'],
  ['22:11', 'tokkyu', 'shinjuku'],
  ['22:17', 'kaisoku', 'shinjuku'],
  ['22:20', 'kakutei', 'shinjuku'],
  ['22:25', 'tokkyu', 'shinjuku'],
  ['22:28', 'kaisoku', 'shinjuku'],
  ['22:31', 'kakutei', 'shinjuku'],
  ['22:37', 'tokkyu', 'shinjuku'],
  ['22:42', 'kukan_kyuko', 'motoyawata'],
  ['22:44', 'kakutei', 'shinjuku'],
  ['22:50', 'tokkyu', 'shinjuku'],
  ['22:54', 'kukan_kyuko', 'motoyawata'],
  ['22:57', 'kakutei', 'shinjuku'],

  ['23:04', 'tokkyu', 'shinjuku'],
  ['23:07', 'kaisoku', 'motoyawata'],
  ['23:10', 'kakutei', 'shinjuku'],
  ['23:19', 'kyuko', 'shinjuku'],
  ['23:22', 'kaisoku', 'shinjuku'],
  ['23:24', 'kakutei', 'shinjuku'],
  ['23:32', 'kakutei', 'shinjuku'],
  ['23:36', 'kyuko', 'shinjuku'],
  ['23:43', 'kakutei', 'sakurajosui'],
  ['23:48', 'kyuko', 'shinjuku'],
  ['23:50', 'kakutei', 'shinjuku'],

  ['00:00', 'tokkyu', 'shinjuku'],
  ['00:05', 'kukan_kyuko', 'sakurajosui'],
  ['00:08', 'kakutei', 'shinsen_shinjuku'],
  ['00:19', 'kakutei', 'sakurajosui'],
  ['00:31', 'kakutei', 'sakurajosui'],
);

const TIMETABLE_DATA = {
  updatedAt: '2026年8月17日改正(ユーザー提供の平日下り時刻表をもとに書き起こし)',
  durationMin: DURATION_MIN,
  typeLabel: TYPE_LABEL,
  typeRank: TYPE_RANK,
  destLabel: DEST_LABEL,
  notReachingShinjuku: NOT_REACHING_SHINJUKU,
  weekday: WEEKDAY_RAW,
  // 土休日ダイヤは未取得。取得でき次第ここに同形式で追加する。
  holiday: null,
};
